export const TEST_USERS = {
  customer: {
    id: "test-customer-1",
    fullName: "Cohan Test Customer",
    username: "cohan_customer",
    email: "customer.test@cohan.local",
    phone: "0900000001",
    roleName: "customer",
    status: "active",
    emailVerified: true,
    phoneVerified: true,
    refRestaurants: [{ id: "test-restaurant-active", name: "Cohan Smoke Bistro" }],
    foodPreferences: {
      diet: ["vegan"],
      allergies: ["peanut"],
      habits: { noOnion: true, noCilantro: false, sugar: 30, spice: "Vừa", ice: "normal" },
      autoNote: "Không đậu phộng",
      updatedAt: "2026-06-01T00:00:00.000Z",
    },
  },
  manager: {
    id: "test-manager-1",
    fullName: "Cohan Test Manager",
    username: "cohan_manager",
    email: "manager.test@cohan.local",
    phone: "0900000002",
    roleName: "manager",
    status: "active",
    emailVerified: true,
    phoneVerified: true,
  },
};

export const TEST_RESTAURANT = {
  id: "test-restaurant-active",
  name: "Cohan Smoke Bistro",
  canOrder: true,
  openingStatus: "open",
  openingStatusReason: "Open for smoke tests",
  coverImage: "/default-restaurant.jpg",
  avatar: "/default-restaurant.jpg",
  description: "Nhà hàng seed cho smoke test",
  priceRange: "$$",
  openingHours: "08:00",
  closingHours: "22:00",
  avgRating: 4.8,
  address: {
    line1: "1 Test Street",
    district: "District 1",
    city: "Ho Chi Minh City",
    country: "VN",
    lat: 10.77,
    lng: 106.69,
  },
};

export const TEST_MENU_ITEMS = [
  {
    id: "test-menu-pho",
    name: "Smoke Test Phở",
    description: "Món đủ metadata FOR YOU cho smoke test",
    basePrice: 79000,
    thumbImage: "/default-dishes.jpg",
    point: 10,
    labels: ["popular"],
    dietTags: [],
    allergenTags: [],
    tasteProfile: { containsOnion: true, containsCilantro: true, sugar: 0, spice: "Vừa" },
    rate: 4.9,
    orderCounter: 120,
    avgPrepTimeMin: 12,
    restaurantId: TEST_RESTAURANT.id,
    menuId: "test-menu-lunch",
    categoryId: "test-category-noodle",
    status: "available",
    inventoryStatus: "IN_STOCK",
    stockWarnings: [],
    servingVariants: [
      { key: "regular", mode: "PORTION", sellQty: 1, sellUnit: "portion", name: "Tô thường", price: 79000 },
      { key: "large", mode: "PORTION", sellQty: 1, sellUnit: "portion", name: "Tô lớn", price: 99000 },
    ],
  },
  {
    id: "test-menu-vegan",
    name: "Smoke Test Vegan Bowl",
    description: "Món vegan có metadata",
    basePrice: 69000,
    thumbImage: "/default-dishes.jpg",
    point: 8,
    labels: ["vegan"],
    dietTags: ["vegan"],
    allergenTags: [],
    tasteProfile: { containsOnion: false, containsCilantro: false, sugar: 30, spice: "Không" },
    rate: 4.7,
    orderCounter: 80,
    avgPrepTimeMin: 10,
    restaurantId: TEST_RESTAURANT.id,
    menuId: "test-menu-lunch",
    categoryId: "test-category-vegan",
    status: "available",
    inventoryStatus: "LOW_STOCK",
    stockWarnings: ["Còn ít rau củ"],
    servingVariants: [{ key: "portion", mode: "PORTION", sellQty: 1, sellUnit: "portion", name: "Phần", price: 69000 }],
  },
];
