import React, { useState, useRef, useEffect, useMemo } from "react";
import { useParams, useNavigate, useLocation } from "react-router-dom";
import { gql, useQuery, useMutation } from "@apollo/client";
import { useNotification } from "../../../hooks/useNotification";
import Modal from "../../../components/common/Modal";
import { readStorageValue } from "@/lib/browserStorage";

import {
  ArrowLeft,
  Save,
  MousePointer2,
  Hand,
  ZoomIn,
  ZoomOut,
  RotateCcw,
  Undo2,
  Sparkles,
  ChevronDown,
  ChevronRight,
  X,
  Trash2,
} from "lucide-react";

import "./FloorPlanDesigner.scss";

export const getAuthHeaders = () => {
  const token =
    readStorageValue("auth_token") ||
    readStorageValue("token") ||
    null;
  return token ? { authorization: `Bearer ${token}` } : {};
};

export const buildAutoLayoutComponentsForRequest = (form) => {
  const sourceComponents = form?.components || {};
  const sourceTables = sourceComponents.tables || {};
  const sourceObjects = sourceComponents.objects || {};
  const standard = Number(sourceTables.standard) || 0;
  const vip = Number(sourceTables.vip) || 0;
  const group = Number(sourceTables.group) || 0;
  const totalTables = standard + vip + group;
  const shouldAutoCreateWalls =
    Number(sourceObjects.door || 0) > 0 ||
    Number(sourceObjects.window || 0) > 0 ||
    Number(sourceObjects.stairs || 0) > 0 ||
    totalTables > 0;
  return {
    ...sourceComponents,
    tables: {
      ...sourceTables,
      standard,
      vip,
      group,
      twoSeat: 0,
      fourSeat: 0,
    },
    objects: {
      ...sourceObjects,
      wall: shouldAutoCreateWalls ? 4 : 0,
    },
  };
};

export const resolveInitialFloorId = (floors = [], requestedFloorId = null) => {
  if (!Array.isArray(floors) || floors.length === 0) return null;
  const requested = requestedFloorId
    ? floors.find((floor) => String(floor.id) === String(requestedFloorId))
    : null;
  return requested?.id || floors[0].id;
};

export const isSmartLayoutGeneratedItem = (item) => {
  const id = String(item?.id || "");
  return (
    item?.source === "smart_layout" ||
    item?.isAutoGenerated === true ||
    id.startsWith("auto_") ||
    id.startsWith("tmp_ai_")
  );
};

export const shouldConfirmReplaceSmartLayout = (items = []) => items.length > 0;

export const sortTablesByCode = (tableA, tableB) => {
  const codeA = String(tableA?.code || tableA?.label || "").trim();
  const codeB = String(tableB?.code || tableB?.label || "").trim();
  return codeA.localeCompare(codeB, undefined, {
    numeric: true,
    sensitivity: "base",
  });
};

export const pickNamingPattern = (codes, fallbackPrefix = "AI") => {
  const stats = new Map();
  let best = null;
  codes.forEach((rawCode) => {
    const cleaned = String(rawCode || "").trim().toUpperCase();
    if (!cleaned) return;
    const match = cleaned.match(/^([A-Z]+)([-_ ]?)(\d+)$/);
    if (!match) return;
    const [, prefix, separator, numText] = match;
    const key = `${prefix}|${separator || ""}`;
    const entry = stats.get(key) || {
      prefix,
      separator: separator || "",
      count: 0,
      maxNumber: 0,
      padding: 0,
    };
    entry.count += 1;
    entry.maxNumber = Math.max(entry.maxNumber, Number(numText) || 0);
    entry.padding = Math.max(entry.padding, numText.length);
    stats.set(key, entry);
    if (!best || entry.count > best.count || (entry.count === best.count && entry.maxNumber > best.maxNumber)) best = entry;
  });
  if (best) return best;
  return {
    prefix: String(fallbackPrefix || "AI").trim().toUpperCase().replace(/\s+/g, "") || "AI",
    separator: "-",
    count: 0,
    maxNumber: 0,
    padding: 0,
  };
};

export const generateSequentialCode = (usedCodes, pattern, offset = 0) => {
  let candidateNumber = (pattern.startNumber ?? pattern.maxNumber + 1) + offset;
  const formatCandidate = () =>
    `${pattern.prefix}${pattern.separator}${String(candidateNumber).padStart(pattern.padding || 0, "0")}`;
  let candidate = formatCandidate();
  while (usedCodes.has(candidate.toUpperCase())) {
    candidateNumber += 1;
    candidate = formatCandidate();
  }
  usedCodes.add(candidate.toUpperCase());
  return candidate;
};

export const getFloorTableNamingPattern = (codes, floorLevel) => {
  const normalizedLevel = String(floorLevel ?? "").trim();
  if (!normalizedLevel) return pickNamingPattern(codes, "T");

  const prefix = `T${normalizedLevel}`;
  const floorCodePattern = new RegExp(`^${prefix}(\\d{2,})$`, "i");
  const floorCodes = codes.filter((code) =>
    floorCodePattern.test(String(code || "").trim()),
  );
  if (floorCodes.length === 0 && codes.length > 0) {
    return pickNamingPattern(codes, prefix);
  }
  return {
    prefix,
    separator: "",
    count: floorCodes.length,
    maxNumber: 0,
    startNumber: 1,
    padding: 2,
  };
};

export const applySmartLayoutToItems = ({ previousItems, generatedTables, generatedDecor, startX, startY, floorLevel, now = Date.now() }) => {
  const existingRealTables = previousItems.filter((item) => item.isRealTable && !item.isLocalOnly).sort(sortTablesByCode);
  const existingCodes = existingRealTables.map((item) => String(item.code || item.label || "").trim()).filter(Boolean);
  const namingPattern = getFloorTableNamingPattern(existingCodes, floorLevel);
  const usedCodes = new Set(previousItems.filter((item) => item.isRealTable).map((item) => String(item.code || item.label || "").trim().toUpperCase()).filter(Boolean));
  const sourceTables = Array.isArray(generatedTables) ? generatedTables : [];
  const mappedTableCount = Math.min(sourceTables.length, existingRealTables.length);
  const mappedExistingTables = existingRealTables.slice(0, mappedTableCount).map((table, index) => {
    const pos = sourceTables[index] || {};
    const canonicalCode = String(table.code || table.label || "").trim();
    if (canonicalCode) usedCodes.add(canonicalCode.toUpperCase());
    return { ...table, x: Number(pos.x) || startX, y: Number(pos.y) || startY, rotation: Number(pos.rotation) || 0, label: canonicalCode || table.label, code: canonicalCode || table.code };
  });
  const newLocalTables = sourceTables.slice(mappedTableCount).map((pos, index) => {
    const generatedCode = generateSequentialCode(usedCodes, namingPattern, index);
    return { id: `tmp_ai_${now}_${index}`, type: "table", x: Number(pos.x) || startX, y: Number(pos.y) || startY, w: 60, h: 60, rotation: Number(pos.rotation) || 0, label: generatedCode, code: generatedCode, capacity: Number(pos.capacity) || 4, tableType: pos.type || "standard", isRealTable: true, isLocalOnly: true, source: "smart_layout", isAutoGenerated: true };
  });

  const mappedById = new Map(mappedExistingTables.map((table) => [table.id, table]));
  const preserved = previousItems.filter((item) => {
    if (item.isLocalOnly && isSmartLayoutGeneratedItem(item)) return false;
    if (item.isRealTable) return true;
    if (item.isLocalOnly) return false;
    if (isSmartLayoutGeneratedItem(item)) return false;
    return true;
  });
  const withUpdatedTables = preserved.map((item) => mappedById.get(item.id) || item);
  const normalizedGeneratedDecor = (generatedDecor || []).map((decor) => ({ ...decor, source: "smart_layout", isAutoGenerated: true }));
  const warnings = [];
  if (sourceTables.length < existingRealTables.length) {
    warnings.push("Sơ đồ yêu cầu ít bàn hơn số bàn hiện có. Hệ thống giữ lại các bàn thật hiện có.");
  }
  return {
    nextItems: [...withUpdatedTables, ...normalizedGeneratedDecor, ...newLocalTables],
    warnings,
    stats: {
      existingTableCount: existingRealTables.length,
      generatedTableCount: sourceTables.length,
      mappedTableCount,
      createdLocalTableCount: newLocalTables.length,
      preservedManualDecorCount: withUpdatedTables.filter((item) => !item.isRealTable).length,
      removedAutoDecorCount: previousItems.filter((item) => !item.isRealTable && isSmartLayoutGeneratedItem(item)).length,
      generatedDecorCount: normalizedGeneratedDecor.length,
    },
  };
};

export const getItemZIndex = (item, isSelected) => {
  if (isSelected) return 100;
  if (item?.isRealTable || item?.type === "table") return 30;
  if (item?.type === "door" || item?.type === "door-double") return 24;
  if (item?.type === "window") return 22;
  if (["cashier", "kitchen", "wc", "buffet"].includes(item?.type)) return 20;
  if (item?.type === "plant") return 18;
  if (item?.type === "half-wall") return 6;
  if (item?.type === "wall") return 5;
  if (item?.type === "rug") return 1;
  return 10;
};

/* --- GRAPHQL --- */
const GET_FLOOR_PLAN_DATA = gql`
  query GetFloorPlanData($restaurantId: ID!) {
    floors(restaurantId: $restaurantId) {
      id
      name
      level
      layout
      isWatching
    }
    tables(restaurantId: $restaurantId, limit: 500) {
      id
      code
      floorId
      position {
        x
        y
        rotation
      }
      type
      capacity
      status
    }
  }
`;

const UPDATE_FLOOR_LAYOUT = gql`
  mutation UpdateFloorLayout($id: ID!, $layout: JSON) {
    updateFloor(input: { id: $id, layout: $layout }) {
      id
    }
  }
`;

const UPDATE_TABLE_POSITION = gql`
  mutation UpdateTablePosition($id: ID!, $position: PositionInput!) {
    updateTable(input: { id: $id, position: $position }) {
      id
    }
  }
`;

const CREATE_TABLE = gql`
  mutation CreateTable($input: CreateTableInput!) {
    createTable(input: $input) {
      id
      code
      floorId
      capacity
      type
      status
      position {
        x
        y
        rotation
      }
    }
  }
`;

const DELETE_TABLE = gql`
  mutation DeleteTable($id: ID!) {
    deleteTable(id: $id)
  }
`;

/* --- PALETTE CONFIG --- */
const PALETTE_ITEMS = [
  {
    category: "Cấu trúc",
    items: [
      { type: "wall", label: "Tường", defaultSize: { w: 140, h: 10 } },
      { type: "half-wall", label: "Vách thấp", defaultSize: { w: 140, h: 8 } },
      { type: "door", label: "Cửa 1 cánh", defaultSize: { w: 70, h: 12 } },
      {
        type: "door-double",
        label: "Cửa 2 cánh",
        defaultSize: { w: 110, h: 12 },
      },
      { type: "window", label: "Cửa sổ", defaultSize: { w: 12, h: 80 } },
      { type: "corridor", label: "Hành lang", defaultSize: { w: 220, h: 14 } },
      { type: "pillar", label: "Cột", defaultSize: { w: 40, h: 40 } },
      { type: "stairs", label: "Cầu thang", defaultSize: { w: 100, h: 60 } },
    ],
  },
  {
    category: "Khu chức năng",
    items: [
      { type: "bar", label: "Quầy bar", defaultSize: { w: 180, h: 60 } },
      { type: "cashier", label: "Thu ngân", defaultSize: { w: 120, h: 50 } },
      { type: "kitchen", label: "Bếp", defaultSize: { w: 140, h: 90 } },
      { type: "buffet", label: "Buffet", defaultSize: { w: 160, h: 70 } },
      { type: "wc", label: "WC", defaultSize: { w: 80, h: 80 } },
      {
        type: "staff-corridor",
        label: "Lối staff",
        defaultSize: { w: 180, h: 14 },
      },
    ],
  },
  {
    category: "Bàn ghế & decor",
    items: [
      { type: "table", label: "Bàn tròn", defaultSize: { w: 60, h: 60 } },
      {
        type: "table-rect-2",
        label: "Bàn 2 người",
        defaultSize: { w: 70, h: 50 },
      },
      {
        type: "table-rect-4",
        label: "Bàn 4 người",
        defaultSize: { w: 90, h: 60 },
      },
      { type: "sofa", label: "Sofa", defaultSize: { w: 120, h: 60 } },
      { type: "plant", label: "Cây", defaultSize: { w: 40, h: 40 } },
      { type: "rug", label: "Thảm", defaultSize: { w: 200, h: 140 } },
    ],
  },
  {
    category: "Ký hiệu",
    items: [
      {
        type: "symbol",
        label: "Thêm ký hiệu",
        defaultSize: { w: 50, h: 50 },
      },
    ],
  },
];

const FloorPlanDesigner = () => {
  const MIN_ITEM_SIZE = 20;

  const { restaurantId } = useParams();
  const navigate = useNavigate();
  const location = useLocation();
  const requestedFloorId = new URLSearchParams(location.search).get("floorId");
  const { showNotification } = useNotification();

  // Apollo
  const { data, loading, refetch } = useQuery(GET_FLOOR_PLAN_DATA, {
    variables: { restaurantId },
    skip: !restaurantId,
    fetchPolicy: "network-only",
  });
  const [updateFloor] = useMutation(UPDATE_FLOOR_LAYOUT);
  const [updateTable] = useMutation(UPDATE_TABLE_POSITION);
  const [createTable] = useMutation(CREATE_TABLE);
  const [deleteTable] = useMutation(DELETE_TABLE);

  // State
  const [floors, setFloors] = useState([]);
  const [activeFloorId, setActiveFloorId] = useState(null);
  const [items, setItems] = useState([]);
  const [selectedId, setSelectedId] = useState(null);
  const [isPaletteCollapsed, setIsPaletteCollapsed] = useState(false);
  const [collapsedGroups, setCollapsedGroups] = useState(new Set());
  const [showSymbolModal, setShowSymbolModal] = useState(false);
  const [symbolForm, setSymbolForm] = useState({ icon: "", name: "" });
  const [showAddTableModal, setShowAddTableModal] = useState(false);
  const [tableForm, setTableForm] = useState({
    code: "",
    capacity: 4,
    type: "standard",
  });
  const [showAiModal, setShowAiModal] = useState(false);
  const defaultAiForm = {
    goal: "balanced",
    components: {
      tables: { standard: 8, vip: 0, group: 0, twoSeat: 0, fourSeat: 0 },
      objects: { plant: 2, door: 1, window: 2, stairs: 0, cashier: 1, kitchen: 1, wc: 1, buffet: 0, wall: 2 },
    },
  };
  const [aiForm, setAiForm] = useState(defaultAiForm);
  const [isLocked, setIsLocked] = useState(false);
  const [lockMessage, setLockMessage] = useState("");
  const [canUndo, setCanUndo] = useState(false);
  const [showExitConfirmModal, setShowExitConfirmModal] = useState(false);
  const [isSavingBeforeExit, setIsSavingBeforeExit] = useState(false);
  const [containerSize, setContainerSize] = useState({
    width: 0,
    height: 0,
  });

  // Viewport & tools
  const [view, setView] = useState({ x: 0, y: 0, scale: 1 });
  const [toolMode, setToolMode] = useState("select");
  const [isSpacePressed, setIsSpacePressed] = useState(false);
  const [isDragging, setIsDragging] = useState(false);

  // Refs
  const dragTarget = useRef(null);
  const startMouse = useRef({ x: 0, y: 0 });
  const startView = useRef({ x: 0, y: 0 });
  const startItem = useRef({ x: 0, y: 0, w: 0, h: 0 });
  const containerRef = useRef(null);
  const savedSnapshotRef = useRef({ decor: new Map(), tables: new Map() });
  const historyRef = useRef([]);
  const historyIndexRef = useRef(-1);
  const dragStartItemsRef = useRef(null);
  const dragMovedRef = useRef(false);
  const lockNotifiedRef = useRef(false);
  const initialFloorResolvedRef = useRef(false);
  const apiBase = (import.meta.env.VITE_API_URL || "http://localhost:4000/graphql").replace(/\/graphql$/i, "");

  // Init floors
  useEffect(() => {
    if (!data?.floors?.length) return;
    setFloors(data.floors);
    if (initialFloorResolvedRef.current) return;
    setActiveFloorId(resolveInitialFloorId(data.floors, requestedFloorId));
    initialFloorResolvedRef.current = true;
  }, [data?.floors, requestedFloorId]);

  // Load items when floor changes
  useEffect(() => {
    if (!activeFloorId || !data) return;

    const currentFloor = data.floors.find((f) => f.id === activeFloorId);
    const currentTables = data.tables.filter(
      (t) => t.floorId === activeFloorId
    );

    const decorItems = (currentFloor?.layout || []).map((item) => ({
      ...item,
      isRealTable: false,
    }));

    const tableItems = currentTables.map((t) => ({
      id: t.id,
      type: "table",
      x: t.position?.x || 0,
      y: t.position?.y || 0,
      w: 60,
      h: 60,
      rotation: t.position?.rotation || 0,
      label: t.code,
      code: t.code,
      isRealTable: true,
      isLocalOnly: false,
    }));

    setItems([...decorItems, ...tableItems]);
    savedSnapshotRef.current = {
      decor: buildDecorMap(decorItems),
      tables: buildTableMap(currentTables),
    };
    historyRef.current = [];
    historyIndexRef.current = -1;
    setCanUndo(false);
    setSelectedId(null);
  }, [activeFloorId, data]);

  useEffect(() => {
    if (!activeFloorId || !data) return;
    const currentFloor = data.floors.find((f) => f.id === activeFloorId);
    const currentTables = data.tables.filter(
      (t) => t.floorId === activeFloorId
    );
    const activeCount = currentTables.filter(
      (t) => t.status && t.status !== "available"
    ).length;
    const isWatching = !!currentFloor?.isWatching;
    if (activeCount > 0) {
      setIsLocked(true);
      setLockMessage(
        `Có ${activeCount} bàn đang hoạt động. Không thể chỉnh sửa sơ đồ.`
      );
    } else if (isWatching) {
      setIsLocked(true);
      setLockMessage("Tầng đang có khách xem sơ đồ. Không thể chỉnh sửa.");
    } else {
      setIsLocked(false);
      setLockMessage("");
    }
  }, [activeFloorId, data]);

  useEffect(() => {
    if (isLocked && lockMessage && !lockNotifiedRef.current) {
      showNotification(lockMessage, "warning");
      lockNotifiedRef.current = true;
    }
    if (!isLocked) lockNotifiedRef.current = false;
  }, [isLocked, lockMessage, showNotification]);

  useEffect(() => {
    const updateSize = () => {
      const node = containerRef.current;
      if (!node) return;
      setContainerSize({
        width: node.clientWidth || 0,
        height: node.clientHeight || 0,
      });
    };
    updateSize();
    window.addEventListener("resize", updateSize);
    return () => window.removeEventListener("resize", updateSize);
  }, []);

  // Shortcuts
  useEffect(() => {
    const handleKeyDown = (e) => {
      if ((e.ctrlKey || e.metaKey) && e.key.toLowerCase() === "z") {
        e.preventDefault();
        handleUndo();
        return;
      }
      if (e.code === "Space" && !e.repeat) setIsSpacePressed(true);
      if ((e.key === "Delete" || e.key === "Backspace") && selectedId) {
        deleteLocalItem();
      }
    };
    const handleKeyUp = (e) => {
      if (e.code === "Space") setIsSpacePressed(false);
    };

    window.addEventListener("keydown", handleKeyDown);
    window.addEventListener("keyup", handleKeyUp);
    return () => {
      window.removeEventListener("keydown", handleKeyDown);
      window.removeEventListener("keyup", handleKeyUp);
    };
  }, [selectedId, items]);

  // Helpers
  const cloneItems = (list) => list.map((item) => ({ ...item }));

  const pushHistory = (snapshot) => {
    historyRef.current = historyRef.current.slice(
      0,
      historyIndexRef.current + 1
    );
    historyRef.current.push(cloneItems(snapshot));
    historyIndexRef.current += 1;
    setCanUndo(historyIndexRef.current >= 0);
  };

  const handleUndo = () => {
    if (isLocked) {
      showNotification(lockMessage || "Không thể chỉnh sửa sơ đồ.", "warning");
      return;
    }
    if (historyIndexRef.current < 0) return;
    const snapshot = historyRef.current[historyIndexRef.current];
    historyIndexRef.current -= 1;
    setItems(cloneItems(snapshot));
    setSelectedId(null);
    setCanUndo(historyIndexRef.current >= 0);
  };

  const buildDecorMap = (decorItems) =>
    new Map(
      decorItems.map((item) => [
        item.id,
        {
          id: item.id,
          type: item.type,
          x: Math.round(item.x),
          y: Math.round(item.y),
          w: item.w,
          h: item.h,
          rotation: item.rotation,
          label: item.label || "",
          icon: item.icon || "",
        },
      ])
    );

  const buildTableMap = (tables) =>
    new Map(
      tables.map((table) => [
        table.id,
        {
          x: Math.round(table.position?.x || 0),
          y: Math.round(table.position?.y || 0),
          rotation: table.position?.rotation || 0,
          isLocalOnly: false,
          code: table.code || "",
        },
      ])
    );

  const hasMapChanges = (nextMap, prevMap) => {
    if (nextMap.size !== prevMap.size) return true;
    for (const [key, nextValue] of nextMap.entries()) {
      const prevValue = prevMap.get(key);
      if (!prevValue) return true;
      if (
        Object.keys(nextValue).some(
          (field) => nextValue[field] !== prevValue[field]
        )
      ) {
        return true;
      }
    }
    return false;
  };

  const findAvailablePosition = ({
    existing,
    startX,
    startY,
    step = 80,
    size = 60,
    maxRadius = 10,
  }) => {
    const isOverlapping = (x, y) =>
      existing.some((t) => {
        const w = t.w || size;
        const h = t.h || size;
        const bx = t.x ?? 0;
        const by = t.y ?? 0;
        return (
          x < bx + w + 10 &&
          x + size + 10 > bx &&
          y < by + h + 10 &&
          y + size + 10 > by
        );
      });
    if (!isOverlapping(startX, startY)) return { x: startX, y: startY };
    for (let r = 1; r <= maxRadius; r += 1) {
      for (let dx = -r; dx <= r; dx += 1) {
        for (let dy = -r; dy <= r; dy += 1) {
          const x = startX + dx * step;
          const y = startY + dy * step;
          if (!isOverlapping(x, y)) return { x, y };
        }
      }
    }
    return { x: startX, y: startY };
  };

  const addItem = (tpl) => {
    if (isLocked) {
      showNotification(lockMessage || "Không thể chỉnh sửa sơ đồ.", "warning");
      return;
    }
    const container = containerRef.current;
    const centerX = (container?.clientWidth || 800) / 2;
    const centerY = (container?.clientHeight || 600) / 2;

    const newItem = {
      id: `d_${Date.now()}`,
      type: tpl.type,
      x: -view.x + centerX / view.scale,
      y: -view.y + centerY / view.scale,
      w: tpl.defaultSize.w,
      h: tpl.defaultSize.h,
      rotation: 0,
      label: tpl.label,
      isRealTable: false,
    };
    setItems((prev) => {
      pushHistory(prev);
      return [...prev, newItem];
    });
    setSelectedId(newItem.id);
    setToolMode("select");
  };

  const updateLocalItem = (id, changes, recordHistory = false) => {
    setItems((prev) => {
      if (recordHistory) pushHistory(prev);
      return prev.map((i) => (i.id === id ? { ...i, ...changes } : i));
    });
  };

  const deleteLocalItem = async () => {
    if (isLocked) {
      showNotification(lockMessage || "Không thể chỉnh sửa sơ đồ.", "warning");
      return;
    }
    if (!selectedId) return;
    const found = items.find((i) => i.id === selectedId);
    if (!found) return;

    const label = found.isRealTable ? `bàn ${found.code || found.label}` : (found.label || found.type || "thành phần");
    if (!window.confirm(`Bạn có chắc muốn xóa ${label}?`)) return;

    if (found.isRealTable && !found.isLocalOnly) {
      try {
        await deleteTable({ variables: { id: found.id } });
        await refetch();
      } catch (err) {
        console.error(err);
        showNotification("Không thể xóa bàn.", "error");
        return;
      }
    } else {
      setItems((prev) => {
        pushHistory(prev);
        return prev.filter((i) => i.id !== selectedId);
      });
    }
    setSelectedId(null);
  };

  // Nudge: dùng cho trường hợp khó kéo bằng chuột
  const handleNudge = (dx, dy, step = 10) => {
    if (isLocked) {
      showNotification(lockMessage || "Không thể chỉnh sửa sơ đồ.", "warning");
      return;
    }
    if (!selectedId) return;
    const current = items.find((i) => i.id === selectedId);
    if (!current) return;
    updateLocalItem(
      selectedId,
      {
        x: Math.round(current.x + dx * step),
        y: Math.round(current.y + dy * step),
      },
      true
    );
  };

  const hasPendingChanges = useMemo(() => {
    const decorItems = items.filter((i) => !i.isRealTable);
    const tableItems = items.filter((i) => i.isRealTable);
    const currentDecorMap = buildDecorMap(decorItems);
    const currentTableMap = new Map(
      tableItems.map((table) => [
        table.id,
        {
          x: Math.round(table.x),
          y: Math.round(table.y),
          rotation: table.rotation,
          isLocalOnly: !!table.isLocalOnly,
          code: table.code || table.label || "",
        },
      ])
    );

    return (
      hasMapChanges(currentDecorMap, savedSnapshotRef.current.decor) ||
      hasMapChanges(currentTableMap, savedSnapshotRef.current.tables)
    );
  }, [items]);

  useEffect(() => {
    const handleBeforeUnload = (e) => {
      if (!hasPendingChanges) return;
      e.preventDefault();
      e.returnValue = "";
    };

    window.addEventListener("beforeunload", handleBeforeUnload);
    return () => window.removeEventListener("beforeunload", handleBeforeUnload);
  }, [hasPendingChanges]);

  const requestExitFloorDesigner = () => {
    if (!hasPendingChanges) {
      navigate(-1);
      return;
    }
    setShowExitConfirmModal(true);
  };

  const handleExitWithoutSaving = () => {
    setShowExitConfirmModal(false);
    navigate(-1);
  };

  const handleSaveBeforeExit = async () => {
    setIsSavingBeforeExit(true);
    const ok = await handleSave();
    setIsSavingBeforeExit(false);
    if (!ok) return;
    setShowExitConfirmModal(false);
    navigate(-1);
  };

  const handleSave = async () => {
    if (!activeFloorId) return false;
    if (isLocked) {
      showNotification(lockMessage || "Không thể chỉnh sửa sơ đồ.", "warning");
      return false;
    }
    try {
      const decorItems = items.filter((i) => !i.isRealTable);
      const tableItems = items.filter((i) => i.isRealTable);
      const currentDecorMap = buildDecorMap(decorItems);
      const currentTableMap = new Map(
        tableItems.map((table) => [
          table.id,
          {
            x: Math.round(table.x),
            y: Math.round(table.y),
            rotation: table.rotation,
            isLocalOnly: !!table.isLocalOnly,
            code: table.code || table.label || "",
          },
        ])
      );

      const decorChanged = hasMapChanges(
        currentDecorMap,
        savedSnapshotRef.current.decor
      );
      const tablesChanged = hasMapChanges(
        currentTableMap,
        savedSnapshotRef.current.tables
      );

      if (!decorChanged && !tablesChanged) {
        showNotification("Không có thay đổi để lưu.", "info");
        return true;
      }

      if (decorChanged) {
        // Keep source/isAutoGenerated in saved floor layout so future AI regeneration can replace prior AI decor after reload.
        await updateFloor({
          variables: { id: activeFloorId, layout: decorItems },
        });
      }

      if (tablesChanged) {
        const localTables = tableItems.filter((table) => table.isLocalOnly);
        if (localTables.length > 0) {
          for (const table of localTables) {
            await createTable({
              variables: {
                input: {
                  restaurantId,
                  floorId: activeFloorId,
                  code: (table.code || table.label || "").trim(),
                  capacity: Number(table.capacity) || 4,
                  type: table.tableType || "standard",
                  status: "available",
                  position: {
                    x: Math.round(table.x),
                    y: Math.round(table.y),
                    rotation: table.rotation,
                  },
                },
              },
            });
          }
        }

        const tablesToSave = tableItems
          .filter((table) => !table.isLocalOnly)
          .filter((table) => {
            const prev = savedSnapshotRef.current.tables.get(table.id);
            if (!prev) return true;
            return (
              prev.x !== Math.round(table.x) ||
              prev.y !== Math.round(table.y) ||
              prev.rotation !== table.rotation
            );
          })
          .map((table) => ({
            id: table.id,
            position: {
              x: Math.round(table.x),
              y: Math.round(table.y),
              rotation: table.rotation,
            },
          }));

        await Promise.all(
          tablesToSave.map((table) => updateTable({ variables: table }))
        );
      }

      const { data: refreshed } = await refetch();
      const latestFloor = refreshed?.floors?.find((f) => f.id === activeFloorId);
      const latestTables = (refreshed?.tables || []).filter(
        (t) => t.floorId === activeFloorId
      );
      savedSnapshotRef.current = {
        decor: buildDecorMap((latestFloor?.layout || []).map((item) => ({ ...item, isRealTable: false }))),
        tables: buildTableMap(latestTables),
      };
      showNotification("✅ Đã lưu thiết kế!", "success");
      return true;
    } catch (err) {
      console.error(err);
      showNotification("Lỗi khi lưu", "error");
      return false;
    }
  };

  const handleAddSymbol = () => {
    if (isLocked) {
      showNotification(lockMessage || "Không thể chỉnh sửa sơ đồ.", "warning");
      return;
    }
    setShowSymbolModal(true);
  };

  const handleCreateSymbol = () => {
    if (!symbolForm.icon.trim()) {
      showNotification("Vui lòng nhập ký hiệu/emoji.", "warning");
      return;
    }
    const container = containerRef.current;
    const centerX = (container?.clientWidth || 800) / 2;
    const centerY = (container?.clientHeight || 600) / 2;
    const newItem = {
      id: `s_${Date.now()}`,
      type: "symbol",
      x: -view.x + centerX / view.scale,
      y: -view.y + centerY / view.scale,
      w: 50,
      h: 50,
      rotation: 0,
      label: symbolForm.name || "Ký hiệu",
      icon: symbolForm.icon,
      isRealTable: false,
    };
    setItems((prev) => {
      pushHistory(prev);
      return [...prev, newItem];
    });
    setSelectedId(newItem.id);
    setShowSymbolModal(false);
    setSymbolForm({ icon: "", name: "" });
  };

  const handleCreateTable = async () => {
    if (!activeFloorId) return false;
    if (isLocked) {
      showNotification(lockMessage || "Không thể chỉnh sửa sơ đồ.", "warning");
      return;
    }
    const normalizedCode = tableForm.code.trim();
    if (!normalizedCode) {
      showNotification("Vui lòng nhập mã bàn.", "warning");
      return;
    }
    const hasDuplicateCode = items.some(
      (item) =>
        item.isRealTable &&
        String(item.code || item.label || "").trim().toUpperCase() ===
          normalizedCode.toUpperCase()
    );
    if (hasDuplicateCode) {
      showNotification("Mã bàn đã tồn tại trên sơ đồ hiện tại.", "warning");
      return;
    }
    const existingTables = items.filter((i) => i.isRealTable);
    const container = containerRef.current;
    const centerX = (container?.clientWidth || 800) / 2;
    const centerY = (container?.clientHeight || 600) / 2;
    const position = findAvailablePosition({
      existing: existingTables,
      startX: -view.x + centerX / view.scale,
      startY: -view.y + centerY / view.scale,
    });

    const localTableItem = {
      id: `tmp_table_${Date.now()}`,
      type: "table",
      x: Math.round(position.x),
      y: Math.round(position.y),
      w: 60,
      h: 60,
      rotation: 0,
      label: normalizedCode,
      code: normalizedCode,
      capacity: Number(tableForm.capacity) || 4,
      tableType: tableForm.type,
      isRealTable: true,
      isLocalOnly: true,
    };

    if (hasPendingChanges) {
      setItems((prev) => {
        pushHistory(prev);
        return [...prev, localTableItem];
      });
      setSelectedId(localTableItem.id);
      setShowAddTableModal(false);
      setTableForm({ code: "", capacity: 4, type: "standard" });
      showNotification(
        `Đã thêm bàn ${normalizedCode} vào bản nháp. Nhấn Lưu để ghi nhận toàn bộ thay đổi.`,
        "success"
      );
      return true;
    }

    try {
      await createTable({
        variables: {
          input: {
            restaurantId,
            floorId: activeFloorId,
            code: normalizedCode,
            capacity: Number(tableForm.capacity) || 4,
            type: tableForm.type,
            status: "available",
            position: {
              x: Math.round(position.x),
              y: Math.round(position.y),
              rotation: 0,
            },
          },
        },
      });
      await refetch();
      showNotification(
        `Đã thêm bàn ${normalizedCode} ở tầng đang chọn. Hãy kiểm tra vị trí nếu cần.`,
        "success"
      );
      setShowAddTableModal(false);
      setTableForm({ code: "", capacity: 4, type: "standard" });
    } catch (err) {
      console.error(err);
      showNotification("Không thể thêm bàn.", "error");
    }
  };

  const handleSmartLayout = () => {
    if (isLocked) {
      showNotification(lockMessage || "Không thể chỉnh sửa sơ đồ.", "warning");
      return;
    }
    setShowAiModal(true);
  };


  const updateAiCount = (section, key, delta) => {
    setAiForm((prev) => {
      const current = Number(prev.components?.[section]?.[key] || 0);
      return {
        ...prev,
        components: {
          ...prev.components,
          [section]: { ...prev.components[section], [key]: Math.max(0, current + delta) },
        },
      };
    });
  };
  const setAiCount = (section, key, value) => {
    setAiForm((prev) => ({
      ...prev,
      components: {
        ...prev.components,
        [section]: {
          ...prev.components[section],
          [key]: Math.max(0, Number(value) || 0),
        },
      },
    }));
  };

  const handleGenerateSmartLayout = async () => {
    if (!activeFloorId) return false;
    if (isLocked) {
      showNotification(lockMessage || "Không thể chỉnh sửa sơ đồ.", "warning");
      return;
    }

    const requestComponents = buildAutoLayoutComponentsForRequest(aiForm);
    const totalTables = Object.values(requestComponents.tables || {}).reduce((sum, n) => sum + (Number(n) || 0), 0);
    if (totalTables <= 0) {
      showNotification("Vui lòng chọn ít nhất 1 bàn", "warning");
      return;
    }
    if (totalTables > 200) {
      showNotification("Tổng số bàn tối đa 200.", "warning");
      return;
    }
    if (shouldConfirmReplaceSmartLayout(items)) {
      const shouldReplace = window.confirm(
        "Tầng này đã có sơ đồ. Bạn muốn tạo lại bố cục hiện tại? Hệ thống sẽ cập nhật vị trí bàn và thay các vật dụng AI cũ, không nhân đôi sơ đồ."
      );
      if (!shouldReplace) return;
    }

    const container = containerRef.current;
    const centerX = (container?.clientWidth || 800) / 2;
    const centerY = (container?.clientHeight || 600) / 2;
    const startX = -view.x + centerX / view.scale - 300;
    const startY = -view.y + centerY / view.scale - 200;

    let layoutPayload = null;
    try {
      const res = await fetch(`${apiBase}/api/ai/floor/generate-layout`, {
        method: "POST",
        credentials: "include",
        headers: {
          "Content-Type": "application/json",
          ...getAuthHeaders(),
        },
        body: JSON.stringify({
          restaurantId,
          floorId: activeFloorId,
          startX,
          startY,
          goal: aiForm.goal,
          components: requestComponents,
          currentItems: items.map((item) => ({ id: item.id, type: item.type, x: item.x, y: item.y, w: item.w, h: item.h, isRealTable: item.isRealTable })),
        }),
      });
      const data = await res.json().catch(() => ({}));
      if (!res.ok || !data?.layout) {
        showNotification(data?.message || "Không thể tạo sơ đồ tự động. Vui lòng thử lại.", "error");
        return;
      }
      layoutPayload = data.layout;
    } catch (err) {
      console.error(err);
      showNotification("Không thể tạo sơ đồ tự động. Vui lòng thử lại.", "error");
      return;
    }

    const { nextItems, warnings: helperWarnings } = applySmartLayoutToItems({
      previousItems: items,
      generatedTables: layoutPayload?.tables || [],
      generatedDecor: layoutPayload?.decor || [],
      startX,
      startY,
      floorLevel: floors.find((floor) => floor.id === activeFloorId)?.level,
    });
    pushHistory(items);
    setItems(nextItems);
    setShowAiModal(false);
    const warnings = [
      ...(Array.isArray(layoutPayload?.meta?.warnings) ? layoutPayload.meta.warnings : []),
      ...helperWarnings,
    ];
    const warningText = warnings.length
      ? ` Lưu ý: ${warnings[0]}${warnings.length > 1 ? ` (+${warnings.length - 1} cảnh báo)` : ""}`
      : "";
    showNotification(`Đã tạo sơ đồ tự động. Nhấn Lưu để ghi nhận.${warningText}`, "success");
  };
  // Mouse handlers
  const handleMouseDown = (e, id = "CANVAS", mode = "move", resizeDir = null) => {
    if (e.button !== 0) return;

    // tránh bôi đen khi kéo
    e.preventDefault();

    const isPanMode =
      mode === "pan" ||
      isSpacePressed ||
      toolMode === "hand" ||
      id === "CANVAS";

    if (isPanMode) {
      setIsDragging(true);
      dragTarget.current = { mode: "pan", id: "CANVAS" };
      startMouse.current = { x: e.clientX, y: e.clientY };
      startView.current = { x: view.x, y: view.y };
      if (id === "CANVAS") setSelectedId(null);
    } else {
      if (isLocked) {
        showNotification(
          lockMessage || "Không thể chỉnh sửa sơ đồ.",
          "warning"
        );
        return;
      }
      e.stopPropagation();
      setIsDragging(true);
      setSelectedId(id);
      dragTarget.current = { mode, id, resizeDir };
      startMouse.current = { x: e.clientX, y: e.clientY };
      const item = items.find((i) => i.id === id);
      if (!item) return;
      startItem.current = { x: item.x, y: item.y, w: item.w, h: item.h };
      dragStartItemsRef.current = cloneItems(items);
      dragMovedRef.current = false;
    }
  };

  const handleMouseMove = (e) => {
    if (!isDragging) return;
    e.preventDefault();

    const dx = e.clientX - startMouse.current.x;
    const dy = e.clientY - startMouse.current.y;

    if (dragTarget.current?.mode === "pan") {
      setView((v) => ({
        ...v,
        x: startView.current.x + dx,
        y: startView.current.y + dy,
      }));
    } else if (dragTarget.current?.mode === "move") {
      const scaledDx = dx / view.scale;
      const scaledDy = dy / view.scale;

      let nx = startItem.current.x + scaledDx;
      let ny = startItem.current.y + scaledDy;

      nx = Math.round(nx / 10) * 10;
      ny = Math.round(ny / 10) * 10;

      dragMovedRef.current = true;
      updateLocalItem(dragTarget.current.id, { x: nx, y: ny });
    } else if (dragTarget.current?.mode === "resize") {
      const scaledDx = dx / view.scale;
      const scaledDy = dy / view.scale;
      const { resizeDir } = dragTarget.current;

      let nx = startItem.current.x;
      let ny = startItem.current.y;
      let nw = startItem.current.w;
      let nh = startItem.current.h;

      if (resizeDir.includes("e")) {
        nw = Math.max(MIN_ITEM_SIZE, startItem.current.w + scaledDx);
      }
      if (resizeDir.includes("s")) {
        nh = Math.max(MIN_ITEM_SIZE, startItem.current.h + scaledDy);
      }
      if (resizeDir.includes("w")) {
        const rightEdge = startItem.current.x + startItem.current.w;
        const nextLeft = Math.min(
          startItem.current.x + scaledDx,
          rightEdge - MIN_ITEM_SIZE
        );
        nx = nextLeft;
        nw = rightEdge - nextLeft;
      }
      if (resizeDir.includes("n")) {
        const bottomEdge = startItem.current.y + startItem.current.h;
        const nextTop = Math.min(
          startItem.current.y + scaledDy,
          bottomEdge - MIN_ITEM_SIZE
        );
        ny = nextTop;
        nh = bottomEdge - nextTop;
      }

      nx = Math.round(nx);
      ny = Math.round(ny);
      nw = Math.round(nw);
      nh = Math.round(nh);

      dragMovedRef.current = true;
      updateLocalItem(dragTarget.current.id, { x: nx, y: ny, w: nw, h: nh });
    }
  };

  const handleMouseUp = () => {
    if (
      dragTarget.current &&
      dragTarget.current.mode !== "pan" &&
      dragMovedRef.current &&
      dragStartItemsRef.current
    ) {
      pushHistory(dragStartItemsRef.current);
    }
    setIsDragging(false);
    dragTarget.current = null;
  };

  const handleWheel = (e) => {
    if (e.ctrlKey || isSpacePressed || toolMode === "hand") {
      e.preventDefault();
      const delta = e.deltaY > 0 ? -0.1 : 0.1;
      setView((v) => ({
        ...v,
        scale: Math.min(Math.max(0.2, v.scale + delta), 4),
      }));
    }
  };

  // Render item on canvas
  const renderItem = (item) => {
    const isSel = selectedId === item.id;
    const style = {
      left: item.x,
      top: item.y,
      width: item.w,
      height: item.h,
      transform: `rotate(${item.rotation}deg)`,
      zIndex: getItemZIndex(item, isSel),
    };
    const canResize = !item.isRealTable;
    const cls = `fp-item ${item.type} ${isSel ? "selected" : ""} ${
      item.isRealTable ? "real" : ""
    }`;

    return (
      <div
        key={item.id}
        className={cls}
        style={style}
        title={item.type === "symbol" ? item.label : undefined}
        onMouseDown={(e) => handleMouseDown(e, item.id, "move")}
      >
        {item.type === "symbol" && (
          <>
            <span className="symbol-icon">{item.icon}</span>
            {item.label && <span className="symbol-tooltip">{item.label}</span>}
          </>
        )}
        {item.type.includes("table") && (
          <span className="label">{item.label}</span>
        )}
        {!item.type.includes("table") &&
          item.label &&
          !["wall", "half-wall", "window", "symbol"].includes(item.type) && (
            <span className="decor-label">{item.label}</span>
          )}

        {isSel && canResize && (
          <>
            <div className="selection-ring" />
            <div
              className="corner nw"
              onMouseDown={(e) => handleMouseDown(e, item.id, "resize", "nw")}
            />
            <div
              className="corner ne"
              onMouseDown={(e) => handleMouseDown(e, item.id, "resize", "ne")}
            />
            <div
              className="corner sw"
              onMouseDown={(e) => handleMouseDown(e, item.id, "resize", "sw")}
            />
            <div
              className="corner se"
              onMouseDown={(e) => handleMouseDown(e, item.id, "resize", "se")}
            />
          </>
        )}
      </div>
    );
  };

  if (loading) return <div className="fp-loading">Đang tải...</div>;
  const selectedItem = items.find((i) => i.id === selectedId);
  const isPanCursor = isSpacePressed || toolMode === "hand";
  const isReadOnly = isLocked;
  const miniMapWidth = 180;
  const miniMapHeight = 140;
  const mapBounds = items.reduce(
    (acc, item) => {
      const right = item.x + (item.w || 0);
      const bottom = item.y + (item.h || 0);
      return {
        minX: Math.min(acc.minX, item.x),
        minY: Math.min(acc.minY, item.y),
        maxX: Math.max(acc.maxX, right),
        maxY: Math.max(acc.maxY, bottom),
      };
    },
    { minX: 0, minY: 0, maxX: 800, maxY: 600 }
  );
  const boundsWidth = Math.max(mapBounds.maxX - mapBounds.minX, 200);
  const boundsHeight = Math.max(mapBounds.maxY - mapBounds.minY, 200);
  const minimapScale = Math.min(
    miniMapWidth / boundsWidth,
    miniMapHeight / boundsHeight
  );
  const viewWorldWidth = containerSize.width / view.scale;
  const viewWorldHeight = containerSize.height / view.scale;
  const viewWorldX = -view.x / view.scale;
  const viewWorldY = -view.y / view.scale;
  const viewportStyle = {
    width: viewWorldWidth * minimapScale,
    height: viewWorldHeight * minimapScale,
    transform: `translate(${(viewWorldX - mapBounds.minX) * minimapScale}px, ${
      (viewWorldY - mapBounds.minY) * minimapScale
    }px)`,
  };

  return (
    <div
      className="fp-layout"
      onMouseMove={handleMouseMove}
      onMouseUp={handleMouseUp}
      onMouseLeave={handleMouseUp}
    >
      {/* HEADER */}
      <header className="fp-header">
        <div className="left-sect">
          <button className="btn-icon" onClick={requestExitFloorDesigner}>
            <ArrowLeft size={20} />
          </button>
          <div className="file-info">
            <div className="title">Floor Plan Designer</div>
            <div className="floor-select-wrap">
              <select
                value={activeFloorId || ""}
                onChange={(e) => {
                  const nextFloorId = e.target.value;
                  setActiveFloorId(nextFloorId);
                  navigate(`/manager/floor-map/${restaurantId}?floorId=${nextFloorId}`, {
                    replace: true,
                  });
                }}
              >
                {floors.map((f) => (
                  <option key={f.id} value={f.id}>
                    {f.name}
                  </option>
                ))}
              </select>
            </div>
          </div>
        </div>

        <div className="center-tools">
          <button
            className={`tool-toggle ${toolMode === "select" ? "active" : ""}`}
            onClick={() => setToolMode("select")}
            title="Select (V)"
          >
            <MousePointer2 size={18} />
          </button>
          <button
            className={`tool-toggle ${toolMode === "hand" ? "active" : ""}`}
            onClick={() => setToolMode("hand")}
            title="Pan (Space)"
          >
            <Hand size={18} />
          </button>
        </div>

        <div className="right-sect">
          <div className="zoom-pill">
            <button
              onClick={() =>
                setView((v) => ({
                  ...v,
                  scale: Math.max(0.2, v.scale - 0.1),
                }))
              }
              title="Thu nhỏ (Ctrl + lăn chuột)"
            >
              <ZoomOut size={16} />
            </button>
            <span>{Math.round(view.scale * 100)}%</span>
            <button
              onClick={() =>
                setView((v) => ({ ...v, scale: Math.min(4, v.scale + 0.1) }))
              }
              title="Phóng to (Ctrl + lăn chuột)"
            >
              <ZoomIn size={16} />
            </button>
          </div>
          <button
            className="btn-secondary"
            onClick={handleUndo}
            disabled={!canUndo || isLocked}
            title="Hoàn tác (Ctrl + Z)"
          >
            <Undo2 size={16} /> Undo
          </button>
          <button
            className="btn-secondary"
            onClick={handleSmartLayout}
            title="Tạo sơ đồ tự động"
            disabled={isLocked}
          >
            <Sparkles size={16} /> Tạo sơ đồ tự động
          </button>
          <button
            className="btn-secondary"
            onClick={() => setShowAddTableModal(true)}
            disabled={isLocked}
            title="Thêm bàn hệ thống"
          >
            ➕ Bàn
          </button>
          <button className="btn-primary" onClick={handleSave} disabled={isLocked}>
            <Save size={16} /> Lưu
          </button>
        </div>
      </header>

      {/* BODY */}
      <div className="fp-body" ref={containerRef}>
        {/* PALETTE */}
        <div
          className={`fp-palette ${isPaletteCollapsed ? "collapsed" : ""}`}
          onMouseDown={(e) => e.stopPropagation()}
        >
          <button
            className="palette-toggle-circle"
            onClick={() => setIsPaletteCollapsed((prev) => !prev)}
            title={isPaletteCollapsed ? "Mở rộng" : "Thu gọn"}
          >
            {isPaletteCollapsed ? (
              <ChevronRight size={18} />
            ) : (
              <ChevronDown size={18} />
            )}
          </button>
          {!isPaletteCollapsed && (
            <>
              <div className="palette-header">
                <span>Bộ công cụ</span>
              </div>
              {PALETTE_ITEMS.map((grp, i) => {
                const isCollapsed = collapsedGroups.has(grp.category);
                return (
                  <div key={i} className="tool-group">
                    <button
                      className="group-label"
                      onClick={() => {
                        setCollapsedGroups((prev) => {
                          const next = new Set(prev);
                          if (next.has(grp.category)) {
                            next.delete(grp.category);
                          } else {
                            next.add(grp.category);
                          }
                          return next;
                        });
                      }}
                    >
                      <span>{grp.category}</span>
                      {isCollapsed ? (
                        <ChevronRight size={14} />
                      ) : (
                        <ChevronDown size={14} />
                      )}
                    </button>
                    {!isCollapsed && (
                      <div className="group-grid">
                        {grp.items.map((t, index) => (
                          <button
                            key={index}
                            className="tool-btn"
                            title={t.label}
                            onMouseDown={(e) => {
                              // tránh bôi đen khi giữ chuột trong sidebar
                              e.preventDefault();
                              e.stopPropagation();
                            }}
                            onClick={() =>
                              t.type === "symbol"
                                ? handleAddSymbol()
                                : addItem(t)
                            }
                          >
                            <div
                              className={`palette-swatch palette-${t.type}`
                                .replace("half-wall", "halfwall")
                                .replace("door-double", "door2")}
                            />
                            <span className="palette-label">{t.label}</span>
                          </button>
                        ))}
                      </div>
                    )}
                  </div>
                );
              })}
            </>
          )}
        </div>

        {/* PROPERTIES PANEL */}
        {selectedItem && (
          <div
            className="fp-properties"
            onMouseDown={(e) => e.stopPropagation()}
          >
            <div className="inspector-head">
              <span
                className={`badge ${
                  selectedItem.isRealTable ? "real" : "decor"
                }`}
              >
                {selectedItem.isRealTable ? "BÀN HỆ THỐNG" : "TRANG TRÍ"}
              </span>
              <button className="close" onClick={() => setSelectedId(null)}>
                <X size={18} />
              </button>
            </div>

            <div className="inspector-content">
              <div className="row-2">
                <div className="input-group">
                  <label>X</label>
                  <input
                    type="number"
                    value={Math.round(selectedItem.x)}
                    onChange={(e) =>
                      updateLocalItem(selectedItem.id, {
                        x: +e.target.value,
                      }, true)
                    }
                    disabled={isReadOnly}
                  />
                </div>
                <div className="input-group">
                  <label>Y</label>
                  <input
                    type="number"
                    value={Math.round(selectedItem.y)}
                    onChange={(e) =>
                      updateLocalItem(selectedItem.id, {
                        y: +e.target.value,
                      }, true)
                    }
                    disabled={isReadOnly}
                  />
                </div>
              </div>

              <div className="row-2">
                <div className="input-group">
                  <label>W</label>
                  <input
                    type="number"
                    value={selectedItem.w}
                    onChange={(e) =>
                      updateLocalItem(selectedItem.id, {
                        w: +e.target.value,
                      }, true)
                    }
                    disabled={isReadOnly}
                  />
                </div>
                <div className="input-group">
                  <label>H</label>
                  <input
                    type="number"
                    value={selectedItem.h}
                    onChange={(e) =>
                      updateLocalItem(selectedItem.id, {
                        h: +e.target.value,
                      }, true)
                    }
                    disabled={isReadOnly}
                  />
                </div>
              </div>

              <div className="input-group">
                <label>Xoay ({selectedItem.rotation}°)</label>
                <input
                  type="range"
                  min="0"
                  max="360"
                  step="5"
                  value={selectedItem.rotation}
                  onChange={(e) =>
                    updateLocalItem(selectedItem.id, {
                      rotation: +e.target.value,
                    }, true)
                  }
                  disabled={isReadOnly}
                />
              </div>

              <div className="input-group">
                <label>Nhãn</label>
                <input
                  value={selectedItem.label || ""}
                  onChange={(e) =>
                    updateLocalItem(selectedItem.id, {
                      label: e.target.value,
                    }, true)
                  }
                  disabled={isReadOnly}
                />
              </div>
              {selectedItem.type === "symbol" && (
                <div className="input-group">
                  <label>Ký hiệu</label>
                  <input
                    value={selectedItem.icon || ""}
                    onChange={(e) =>
                      updateLocalItem(
                        selectedItem.id,
                        { icon: e.target.value },
                        true
                      )
                    }
                    placeholder="Ví dụ: 🍀 hoặc :)"
                    disabled={isReadOnly}
                  />
                </div>
              )}

              {/* NUDGE CONTROLS */}
              <div className="nudge-group">
                <label>Di chuyển (giữ Shift: 1px)</label>
                <div className="nudge-grid">
                  <button
                    onClick={(e) => handleNudge(0, -1, e.shiftKey ? 1 : 10)}
                    disabled={isReadOnly}
                  >
                    ↑
                  </button>
                  <button
                    onClick={(e) => handleNudge(-1, 0, e.shiftKey ? 1 : 10)}
                    disabled={isReadOnly}
                  >
                    ←
                  </button>
                  <button
                    onClick={(e) => handleNudge(1, 0, e.shiftKey ? 1 : 10)}
                    disabled={isReadOnly}
                  >
                    →
                  </button>
                  <button
                    onClick={(e) => handleNudge(0, 1, e.shiftKey ? 1 : 10)}
                    disabled={isReadOnly}
                  >
                    ↓
                  </button>
                </div>
              </div>

              <div className="divider" />
              <button
                className="btn-danger"
                onClick={deleteLocalItem}
                disabled={isReadOnly}
              >
                <Trash2 size={16} />{" "}
                Xóa
              </button>
            </div>
          </div>
        )}

        {/* CANVAS */}
        <div
          className={`fp-canvas-viewport ${
            isPanCursor || isDragging ? (isDragging ? "grabbing" : "grab") : ""
          }`}
          onMouseDown={(e) => handleMouseDown(e, "CANVAS")}
          onWheel={handleWheel}
        >
          <div
            className="fp-canvas-world"
            style={{
              transform: `translate(${view.x}px, ${view.y}px) scale(${view.scale})`,
            }}
          >
            <div className="dot-grid" />
            {items.map((item) => renderItem(item))}
          </div>
          {isLocked && (
            <div className="fp-lock-overlay">
              <div className="lock-card">
                <strong>Không thể chỉnh sửa</strong>
                <p>{lockMessage}</p>
              </div>
            </div>
          )}
        </div>

        {/* RESET VIEW BUTTON */}
        <div className="fp-controls" onMouseDown={(e) => e.stopPropagation()}>
          <button
            onClick={() => setView({ x: 0, y: 0, scale: 1 })}
            title="Reset View"
          >
            <RotateCcw size={16} />
          </button>
        </div>

        {/* MINI MAP */}
        <div className="fp-minimap">
          <div className="minimap-title">Tổng quan</div>
          <div
            className="minimap-canvas"
            style={{ width: miniMapWidth, height: miniMapHeight }}
          >
            {items.map((item) => (
              <div
                key={`mini_${item.id}`}
                className={`minimap-item ${item.isRealTable ? "table" : "decor"}`}
                style={{
                  width: Math.max(item.w * minimapScale, 4),
                  height: Math.max(item.h * minimapScale, 4),
                  transform: `translate(${
                    (item.x - mapBounds.minX) * minimapScale
                  }px, ${(item.y - mapBounds.minY) * minimapScale}px)`,
                }}
              />
            ))}
            <div className="minimap-viewport" style={viewportStyle} />
          </div>
        </div>
      </div>

      <Modal
        isOpen={showSymbolModal}
        onClose={() => setShowSymbolModal(false)}
        className="fp-modal-shell fp-modal-shell--symbol"
        title="Thêm ký hiệu"
      >
        <div className="fp-modal">
          <div className="fp-modal-row">
            <label>Tên ký hiệu</label>
            <input
              value={symbolForm.name}
              onChange={(e) =>
                setSymbolForm((prev) => ({ ...prev, name: e.target.value }))
              }
              placeholder="Ví dụ: Khu check-in"
            />
          </div>
          <div className="fp-modal-row">
            <label>Icon/Emoji</label>
            <input
              value={symbolForm.icon}
              onChange={(e) =>
                setSymbolForm((prev) => ({ ...prev, icon: e.target.value }))
              }
              placeholder="Ví dụ: ⭐️ hoặc :)"
            />
          </div>
          <div className="fp-modal-actions">
            <button className="btn-secondary" onClick={() => setShowSymbolModal(false)}>
              Hủy
            </button>
            <button className="btn-primary" onClick={handleCreateSymbol}>
              Thêm ký hiệu
            </button>
          </div>
        </div>
      </Modal>

      <Modal
        isOpen={showAddTableModal}
        onClose={() => setShowAddTableModal(false)}
        className="fp-modal-shell fp-modal-shell--table"
        title="Thêm bàn vào sơ đồ"
      >
        <div className="fp-modal">
          <div className="fp-modal-intro">
            <strong>Thêm bàn nhanh</strong>
            <p>
              Bàn mới sẽ được đặt ở vị trí gần nhất không chồng lấn trong sơ đồ.
            </p>
          </div>
          <div className="fp-modal-row">
            <label>Mã bàn</label>
            <input
              value={tableForm.code}
              onChange={(e) =>
                setTableForm((prev) => ({ ...prev, code: e.target.value }))
              }
              placeholder="VD: A1, B2..."
            />
          </div>
          <div className="fp-modal-row">
            <label>Sức chứa</label>
            <input
              type="number"
              value={tableForm.capacity}
              onChange={(e) =>
                setTableForm((prev) => ({ ...prev, capacity: e.target.value }))
              }
            />
          </div>
          <div className="fp-modal-row">
            <label>Loại bàn</label>
            <select
              value={tableForm.type}
              onChange={(e) =>
                setTableForm((prev) => ({ ...prev, type: e.target.value }))
              }
            >
              <option value="standard">Trong nhà</option>
              <option value="vip">VIP</option>
              <option value="outdoor">Ngoài trời</option>
              <option value="bar">Bar</option>
            </select>
          </div>
          <div className="fp-modal-actions">
            <button className="btn-secondary" onClick={() => setShowAddTableModal(false)}>
              Hủy
            </button>
            <button className="btn-primary" onClick={handleCreateTable}>
              Thêm bàn
            </button>
          </div>
        </div>
      </Modal>

      <Modal
        isOpen={showAiModal}
        onClose={() => setShowAiModal(false)}
        className="fp-modal-shell fp-modal-shell--ai"
        title="Tạo sơ đồ tự động"
      >
        <div className="fp-modal">
          <div className="fp-modal-intro"><strong>Thiết lập nhanh</strong><p>Chọn số lượng bàn và các khu vực cần có. Hệ thống sẽ tự tính tường, lối đi và bố cục.</p></div>
          {[['tables','Bàn', [['standard','Bàn thường','Mặc định 4 chỗ, dùng cho đa số khách.'],['vip','Bàn VIP','Không gian riêng hơn, hệ thống sẽ bố trí tách nhẹ.'],['group','Bàn nhóm / gia đình','Bàn lớn cho nhóm đông, khoảng 6–8 chỗ.']]], ['objects','Khu vực & vật dụng', [['plant','Cây trang trí'],['door','Cửa'],['window','Cửa sổ'],['stairs','Cầu thang'],['cashier','Quầy thu ngân'],['kitchen','Bếp'],['wc','WC'],['buffet','Buffet']]]].map(([section,title,entries]) => (
            <div key={section} className="fp-ai-section">
              <h4>{title}</h4>
              {entries.map(([key,label,helperText]) => (
                <div className="fp-modal-row" key={key}>
                  <label>{label}{helperText ? <small>{helperText}</small> : null}</label>
                  <div className="fp-stepper">
                    <button type="button" onClick={() => updateAiCount(section, key, -1)}>-</button>
                    <input type="number" min="0" value={aiForm.components?.[section]?.[key] ?? 0} onChange={(e) => setAiCount(section, key, e.target.value)} />
                    <button type="button" onClick={() => updateAiCount(section, key, 1)}>+</button>
                  </div>
                </div>
              ))}
            </div>
          ))}
          <p className="fp-ai-note">Hệ thống sẽ tự tạo tường/khung phòng phù hợp với sơ đồ.</p>
          <div className="fp-ai-section"><h4>Mục tiêu bố cục</h4><div className="fp-modal-row"><select value={aiForm.goal} onChange={(e)=>setAiForm((p)=>({...p,goal:e.target.value}))}><option value="balanced">Cân bằng</option><option value="capacity">Nhiều bàn nhất</option><option value="spacious">Đẹp / rộng rãi</option><option value="vip">Sang / VIP</option></select></div></div>
          <div className="fp-modal-actions">
            <button className="btn-secondary" onClick={() => setAiForm(defaultAiForm)}>Reset mặc định</button>
            <button className="btn-secondary" onClick={() => setShowAiModal(false)}>Hủy</button>
            <button className="btn-primary" onClick={handleGenerateSmartLayout}>Generate sơ đồ</button>
          </div>
        </div>
      </Modal>

      <Modal
        isOpen={showExitConfirmModal}
        onClose={() => setShowExitConfirmModal(false)}
        className="fp-modal-shell fp-modal-shell--exit"
        title="Rời trang thiết kế"
      >
        <div className="fp-modal">
          <div className="fp-modal-intro">
            <strong>Bạn có thay đổi chưa lưu</strong>
            <p>
              Bạn muốn lưu trước khi thoát khỏi trang thiết kế sơ đồ không?
            </p>
          </div>
          <div className="fp-modal-actions fp-modal-actions--exit">
            <button className="btn-secondary" onClick={() => setShowExitConfirmModal(false)}>
              Ở lại
            </button>
            <button className="btn-secondary" onClick={handleExitWithoutSaving}>
              Thoát không lưu
            </button>
            <button
              className="btn-primary"
              onClick={handleSaveBeforeExit}
              disabled={isSavingBeforeExit}
            >
              {isSavingBeforeExit ? "Đang lưu..." : "Lưu và thoát"}
            </button>
          </div>
        </div>
      </Modal>
    </div>
  );
};

export default FloorPlanDesigner;
