scalar DateTime
scalar JSON

type Query {
  _empty: String
}

type Mutation {
  _empty: String
}

type Subscription {
  _empty: String
}

input UploadOrderItemProofInput {
  restaurantId: ID
  orderId: ID!
  orderItemId: ID!
  proofImages: [String!]!
  note: String
}

extend type CustomerTrackingItem {
  proofImages: [String!]!
  requiresProofImage: Boolean!
  proofUploaded: Boolean!
}

extend type Mutation {
  uploadOrderItemProof(input: UploadOrderItemProofInput!): UpdateOrderItemStatusPayload!
}
