type Category {
  id: ID!
  restaurantId: ID
  timeSlot: TimeSlot
  name: String!
  icon: String
  order: Int
  isActive: Boolean
  menuItemCount: Int!
  createdAt: DateTime
  updatedAt: DateTime
}

input CreateCategoryInput {
  restaurantId: ID
  timeSlot: TimeSlot
  name: String!
  icon: String
  order: Int
  isActive: Boolean
}

type CategoryMenu {
  id: ID!
  restaurantId: ID!
  name: String!
  icon: String
  description: String
  coverImage: String
  isActive: Boolean
  createdAt: DateTime
  updatedAt: DateTime
}

input UpdateCategoryInput {
  id: ID!
  name: String
  icon: String
  order: Int
  isActive: Boolean
}

extend type Query {
  categories(
    restaurantId: ID!
    timeSlot: TimeSlot!
    menuId: ID
  ): [Category!]!
  customerMenuCategories(
    restaurantId: ID!
    timeSlot: TimeSlot!
    menuId: ID
  ): [Category!]!

  topCategoriesByMenuItemCount(
    restaurantId: ID!
    timeSlot: TimeSlot!
    menuId: ID
    limit: Int = 6
  ): [Category!]!

  topGlobalCategoriesByMenuItemCount(
    timeSlot: TimeSlot
    limit: Int = 6
  ): [Category!]!

  categoryMenus(restaurantId: ID!): [CategoryMenu!]!
  categoryMenu(id: ID!): CategoryMenu
}

input CreateCategoryMenuInput {
  restaurantId: ID!
  name: String!
  icon: String
  description: String
  coverImage: String
  isActive: Boolean
}

input UpdateCategoryMenuInput {
  id: ID!
  name: String
  icon: String
  description: String
  coverImage: String
  isActive: Boolean
}

extend type Mutation {
  createCategory(input: CreateCategoryInput!): Category!
  updateCategory(input: UpdateCategoryInput!): Category!
  deleteCategory(id: ID!): Boolean!

  createCategoryMenu(input: CreateCategoryMenuInput!): CategoryMenu!
  updateCategoryMenu(input: UpdateCategoryMenuInput!): CategoryMenu!
  deleteCategoryMenu(id: ID!): Boolean!
}
