type Role {
  id: ID!
  name: String!
  slug: String!
  description: String
  department: DepartmentType
  isSystem: Boolean
  parentRole: ParentRole
  directPermissions: [Permission!]!
  permissions: [Permission!]!
  users: [User!]!
  createdAt: String
  updatedAt: String
}

type ParentRole {
  id: ID!
  name: String!
  slug: String!
  description: String
  permissions: [Permission!]!
  createdAt: String
  updatedAt: String
}

input CreateRoleInput {
  name: String!
  slug: String!
  description: String
  department: DepartmentType
  parentRoleId: ID! # bắt buộc: liên kết tới ParentRole
  permissionIds: [ID!]
}

input UpdateRoleInput {
  id: ID!
  name: String
  description: String
  department: DepartmentType
  parentRoleId: ID # optional: đổi parentRole
  permissionIds: [ID!]
}

input CreateParentRoleInput {
  name: String!
  slug: String!
  description: String
  permissionIds: [ID!]
}

input UpdateParentRoleInput {
  id: ID!
  name: String
  slug: String
  description: String
  permissionIds: [ID!]
}

extend type Query {
  role(search: String, parentRoleId: ID): [Role!]!
  parentRoles(search: String): [ParentRole!]!
}

extend type Mutation {
  createRole(input: CreateRoleInput!): Role!
  updateRole(input: UpdateRoleInput!): Role!
  deleteRole(id: ID!): Boolean!

  createParentRole(input: CreateParentRoleInput!): ParentRole!
  updateParentRole(input: UpdateParentRoleInput!): ParentRole!
  deleteParentRole(id: ID!): Boolean!
}
