type Role {
  id: ID!
  name: String!
  slug: String!
  description: String
  parent: String
  isSystem: Boolean
  permissions: [Permission!]!
  users: [User!]!
  createdAt: String
  updatedAt: String
}

input CreateRoleInput {
  name: String!
  slug: String!
  description: String
  parent: String
  permissionIds: [ID!]
}

input UpdateRoleInput {
  id: ID!
  name: String
  description: String
  parent: String
  permissionIds: [ID!]
}
extend type Query {
  role(search: String, parent: String): [Role!]!
}

extend type Mutation {
  createRole(input: CreateRoleInput!): Role!
  updateRole(input: UpdateRoleInput!): Role!
  deleteRole(id: ID!): Boolean!
  assignRolesToUser(userId: ID!, roleIds: [ID!]!): User!
  revokeRolesFromUser(userId: ID!, roleIds: [ID!]!): User!
}
