import React, { useContext, useMemo, useState } from "react";
import { gql, useLazyQuery, useMutation, useQuery } from "@apollo/client";
import { AuthContext } from "@/context/AuthContext";

const Q = gql`query ManagerAiKnowledge($restaurantId: ID!, $filter: AiChatbotKnowledgeFilterInput) { restaurantAiChatbotKnowledge(restaurantId: $restaurantId, filter: $filter) { id restaurantId title content category tags enabled priority sourceType updatedAt } }`;
const Q_SUGGESTIONS = gql`query ManagerAiKnowledgeSuggestions($restaurantId: ID!, $filter: AiChatbotKnowledgeSuggestionFilterInput) { restaurantAiChatbotKnowledgeSuggestions(restaurantId: $restaurantId, filter: $filter) { id restaurantId question triggerType confidence occurrenceCount lastAskedAt suggestedTitle suggestedContent category tags status approvedKnowledgeItemId } }`;
const C = gql`mutation CreateAiKnowledge($input: CreateAiChatbotKnowledgeItemInput!) { createRestaurantAiChatbotKnowledgeItem(input: $input) { id } }`;
const U = gql`mutation UpdateAiKnowledge($input: UpdateAiChatbotKnowledgeItemInput!) { updateRestaurantAiChatbotKnowledgeItem(input: $input) { id } }`;
const D = gql`mutation DeleteAiKnowledge($id: ID!) { deleteRestaurantAiChatbotKnowledgeItem(id: $id) }`;
const APPROVE = gql`mutation ApproveAiSuggestion($id: ID!, $input: ApproveAiChatbotKnowledgeSuggestionInput!) { approveRestaurantAiChatbotKnowledgeSuggestion(id: $id, input: $input) { id } }`;
const DISMISS = gql`mutation DismissAiSuggestion($id: ID!) { dismissRestaurantAiChatbotKnowledgeSuggestion(id: $id) }`;
const DELETE_S = gql`mutation DeleteAiSuggestion($id: ID!) { deleteRestaurantAiChatbotKnowledgeSuggestion(id: $id) }`;
const Q_FEEDBACK = gql`query ManagerAiFeedback($restaurantId: ID!, $filter: AiChatbotAnswerFeedbackFilterInput) { restaurantAiChatbotAnswerFeedback(restaurantId: $restaurantId, filter: $filter) { id question answer reason confidence rating status createdAt } }`;
const FEEDBACK_REVIEW = gql`mutation MarkAiFeedbackReviewed($id: ID!) { markAiChatbotAnswerFeedbackReviewed(id: $id) }`;
const FEEDBACK_IGNORE = gql`mutation IgnoreAiFeedback($id: ID!) { ignoreAiChatbotAnswerFeedback(id: $id) }`;
const FEEDBACK_CONVERT = gql`mutation ConvertAiFeedback($id: ID!) { convertAiChatbotFeedbackToSuggestion(id: $id) }`;
const Q_SAFETY = gql`query ManagerAiSafety($restaurantId: ID!, $filter: AiChatbotSafetyRuleFilterInput) { restaurantAiChatbotSafetyRules(restaurantId: $restaurantId, filter: $filter) { id restaurantId ruleType pattern responseMessage enabled priority } }`;
const C_SAFETY = gql`mutation CreateAiSafety($input: CreateAiChatbotSafetyRuleInput!) { createRestaurantAiChatbotSafetyRule(input: $input) { id } }`;
const U_SAFETY = gql`mutation UpdateAiSafety($input: UpdateAiChatbotSafetyRuleInput!) { updateRestaurantAiChatbotSafetyRule(input: $input) { id } }`;
const D_SAFETY = gql`mutation DeleteAiSafety($id: ID!) { deleteRestaurantAiChatbotSafetyRule(id: $id) }`;
const Q_EVAL = gql`query EvalPrompt($input: EvaluateAiChatbotPromptInput!) { evaluateRestaurantAiChatbotPrompt(input: $input) { answer intent confidence isFallback handoffSuggested handoffReason handoffMessage quickReplies actions { type label href } sources { type id label } contextSummary { restaurantCount menuItemCount couponCount orderCount reservationCount } knowledgeMatches { id title category sourceType score } safetyResult { blocked outOfScope disclaimers handoffSuggested matchedRuleIds } } }`;
const Q_EVAL_CASES = gql`query EvalCases($restaurantId: ID!) { restaurantAiChatbotEvaluationCases(restaurantId: $restaurantId) { id question expectedBehavior category tags enabled } }`;
const M_CREATE_CASE = gql`mutation CreateEvalCase($input: CreateAiChatbotEvaluationCaseInput!) { createRestaurantAiChatbotEvaluationCase(input: $input) { id } }`;
const Q_RUN_SET = gql`query RunEvalSet($input: RunAiChatbotEvaluationSetInput!) { runRestaurantAiChatbotEvaluationSet(input: $input) { caseId question answer confidence isFallback handoffSuggested safetyResult { blocked } } }`;
const TABS = ["knowledge", "suggestions", "feedback", "safety", "evaluation"];
const blank = { id: "", title: "", content: "", category: "", tags: "", enabled: true, priority: 0, sourceType: "manual" };
const safetyBlank = { id: "", ruleType: "blocked_topic", pattern: "", responseMessage: "", enabled: true, priority: 0 };

export default function AiChatbotKnowledgePage() { const { restaurants = [] } = useContext(AuthContext) || {}; const [activeTab, setActiveTab] = useState("knowledge"); const [restaurantId, setRestaurantId] = useState(""); const [search, setSearch] = useState(""); const [enabled, setEnabled] = useState("all"); const [form, setForm] = useState(blank); const [suggestionStatus, setSuggestionStatus] = useState("pending"); const [suggestionTrigger, setSuggestionTrigger] = useState("all"); const [suggestionSearch, setSuggestionSearch] = useState(""); const [feedbackRating, setFeedbackRating] = useState("not_helpful"); const [feedbackStatus, setFeedbackStatus] = useState("new"); const [safetyForm, setSafetyForm] = useState(safetyBlank); const [safetySearch, setSafetySearch] = useState(""); const [safetyType, setSafetyType] = useState("all"); const [safetyEnabled, setSafetyEnabled] = useState("all"); const [evalMessage, setEvalMessage] = useState(""); const [evalResult, setEvalResult] = useState(null); const [evalSetResults, setEvalSetResults] = useState([]); const [notice, setNotice] = useState("");
const rid = restaurantId || restaurants?.[0]?.id || "";
const filter = useMemo(() => ({ search: search || undefined, enabled: enabled === "all" ? undefined : enabled === "on" }), [search, enabled]);
const suggestionFilter = useMemo(() => ({ status: suggestionStatus === "all" ? undefined : suggestionStatus, triggerType: suggestionTrigger === "all" ? undefined : suggestionTrigger, search: suggestionSearch || undefined }), [suggestionStatus, suggestionTrigger, suggestionSearch]);
const { data, loading, error, refetch } = useQuery(Q, { skip: !rid, variables: { restaurantId: rid, filter } });
const { data: suggestionData, loading: suggestionLoading, error: suggestionError, refetch: refetchSuggestion } = useQuery(Q_SUGGESTIONS, { skip: !rid, variables: { restaurantId: rid, filter: suggestionFilter } });
const { data: feedbackData, loading: feedbackLoading, error: feedbackError, refetch: refetchFeedback } = useQuery(Q_FEEDBACK, { skip: !rid, variables: { restaurantId: rid, filter: { rating: feedbackRating === "all" ? undefined : feedbackRating, status: feedbackStatus === "all" ? undefined : feedbackStatus } } });
const { data: safetyData, loading: safetyLoading, error: safetyError, refetch: refetchSafety } = useQuery(Q_SAFETY, { skip: !rid, variables: { restaurantId: rid, filter: { search: safetySearch || undefined, ruleType: safetyType === "all" ? undefined : safetyType, enabled: safetyEnabled === "all" ? undefined : safetyEnabled === "on" } } });
const [createItem] = useMutation(C); const [updateItem] = useMutation(U); const [deleteItem] = useMutation(D); const [approveSuggestion] = useMutation(APPROVE); const [dismissSuggestion] = useMutation(DISMISS); const [deleteSuggestion] = useMutation(DELETE_S); const [markFeedbackReviewed] = useMutation(FEEDBACK_REVIEW); const [ignoreFeedback] = useMutation(FEEDBACK_IGNORE); const [convertFeedback] = useMutation(FEEDBACK_CONVERT); const [createSafety] = useMutation(C_SAFETY); const [updateSafety] = useMutation(U_SAFETY); const [deleteSafety] = useMutation(D_SAFETY); const [runEvalPrompt, { loading: evaluating }] = useLazyQuery(Q_EVAL, { fetchPolicy: "no-cache" }); const { data: evalCasesData, loading: evalCasesLoading, error: evalCasesError, refetch: refetchEvalCases } = useQuery(Q_EVAL_CASES, { skip: !rid, variables: { restaurantId: rid } }); const [createEvalCase] = useMutation(M_CREATE_CASE); const [runEvalSet, { loading: runningSet }] = useLazyQuery(Q_RUN_SET, { fetchPolicy: "no-cache" });
const rows = data?.restaurantAiChatbotKnowledge || []; const suggestionRows = suggestionData?.restaurantAiChatbotKnowledgeSuggestions || []; const feedbackRows = feedbackData?.restaurantAiChatbotAnswerFeedback || []; const safetyRows = safetyData?.restaurantAiChatbotSafetyRules || [];
const onFail = (e, l) => setNotice(`${l} thất bại: ${e?.message || "Lỗi không xác định"}`);

return <section style={{ padding: 16 }}><h2>AI Chatbot Manager Tools</h2><label>Nhà hàng <select value={rid} onChange={(e) => setRestaurantId(e.target.value)}>{restaurants.map((r) => <option key={r.id} value={r.id}>{r.name}</option>)}</select></label><div>{TABS.map((tab) => <button key={tab} onClick={() => setActiveTab(tab)} disabled={activeTab===tab}>{tab}</button>)}</div>{notice ? <p>{notice}</p> : null}
{activeTab==="knowledge" && <div><h3>Knowledge Base</h3>{loading ? <p>Đang tải...</p> : error ? <p>{error.message}</p> : !rows.length ? <p>Chưa có knowledge item.</p> : <ul>{rows.map((item)=><li key={item.id}><strong>{item.title}</strong><button onClick={()=>setForm({...item,tags:(item.tags||[]).join(", ")})}>Sửa</button><button onClick={async()=>{try{await updateItem({variables:{input:{id:item.id,enabled:!item.enabled}}});refetch?.();setNotice("Cập nhật trạng thái knowledge thành công.");}catch(e){onFail(e,"Cập nhật knowledge")}}}>{item.enabled?"Tắt":"Bật"}</button><button onClick={async()=>{if(!window.confirm("Xóa mục này?"))return;try{await deleteItem({variables:{id:item.id}});refetch?.();setNotice("Đã xóa knowledge item.");}catch(e){onFail(e,"Xóa knowledge")}}}>Xóa</button></li>)}</ul>}<form onSubmit={async(e)=>{e.preventDefault(); try{const payload={...form,restaurantId:rid,tags:String(form.tags||"").split(",").map((s)=>s.trim()).filter(Boolean)}; if(form.id) await updateItem({variables:{input:{...payload,id:form.id}}}); else await createItem({variables:{input:payload}}); setForm(blank); refetch?.(); setNotice("Lưu knowledge item thành công.");}catch(err){onFail(err,"Lưu knowledge")}}}><input required value={form.title} onChange={(e)=>setForm((f)=>({...f,title:e.target.value}))}/><textarea required value={form.content} onChange={(e)=>setForm((f)=>({...f,content:e.target.value}))}/><button type="submit">Lưu</button></form></div>}
{activeTab==="suggestions" && <div><h3>Suggestions</h3>{suggestionLoading ? <p>Đang tải gợi ý...</p> : suggestionError ? <p>{suggestionError.message}</p> : !suggestionRows.length ? <p>Không có suggestion.</p> : <ul>{suggestionRows.map((s)=><li key={s.id}>{s.question} [{s.status}] {s.status==="pending" ? <><button onClick={async()=>{try{await approveSuggestion({variables:{id:s.id,input:{title:s.suggestedTitle||s.question,content:s.suggestedContent||s.question,category:s.category||"",tags:s.tags||[],sourceType:"faq",enabled:true,priority:50}}});refetchSuggestion?.();refetch?.();setNotice("Đã duyệt suggestion.");}catch(e){onFail(e,"Duyệt suggestion")}}}>Approve</button><button onClick={async()=>{try{await dismissSuggestion({variables:{id:s.id}});refetchSuggestion?.();setNotice("Đã dismiss suggestion.");}catch(e){onFail(e,"Dismiss suggestion")}}}>Dismiss</button></>:null}<button onClick={async()=>{try{await deleteSuggestion({variables:{id:s.id}});refetchSuggestion?.();setNotice("Đã xóa suggestion.");}catch(e){onFail(e,"Xóa suggestion")}}}>Delete</button></li>)}</ul>}</div>}
{activeTab==="feedback" && <div><h3>Feedback</h3>{feedbackLoading?<p>Đang tải feedback...</p>:feedbackError?<p>{feedbackError.message}</p>:!feedbackRows.length?<p>Không có feedback.</p>:<ul>{feedbackRows.map((f)=><li key={f.id}>{f.question}<button onClick={async()=>{try{await markFeedbackReviewed({variables:{id:f.id}});refetchFeedback?.();setNotice("Đã đánh dấu reviewed.");}catch(e){onFail(e,"Review feedback")}}}>Reviewed</button><button onClick={async()=>{try{await ignoreFeedback({variables:{id:f.id}});refetchFeedback?.();setNotice("Đã bỏ qua feedback.");}catch(e){onFail(e,"Ignore feedback")}}}>Ignore</button><button onClick={async()=>{try{await convertFeedback({variables:{id:f.id}});refetchFeedback?.();refetchSuggestion?.();setNotice("Đã convert feedback thành suggestion.");}catch(e){onFail(e,"Convert feedback")}}}>Convert</button></li>)}</ul>}</div>}
{activeTab==="safety" && <div><h3>Safety</h3>{safetyLoading?<p>Đang tải safety rules...</p>:safetyError?<p>{safetyError.message}</p>:!safetyRows.length?<p>Chưa có safety rule.</p>:<ul>{safetyRows.map((r)=><li key={r.id}>{r.ruleType}<button onClick={()=>setSafetyForm({...r})}>Sửa</button><button onClick={async()=>{try{await deleteSafety({variables:{id:r.id}});refetchSafety?.();setNotice("Đã xóa safety rule.");}catch(e){onFail(e,"Xóa safety")}}}>Xóa</button></li>)}</ul>}<form onSubmit={async(e)=>{e.preventDefault();try{const payload={...safetyForm,restaurantId:rid,priority:Number(safetyForm.priority||0)}; if(safetyForm.id) await updateSafety({variables:{input:{...payload,id:safetyForm.id}}}); else await createSafety({variables:{input:payload}}); setSafetyForm(safetyBlank); refetchSafety?.(); setNotice("Lưu safety rule thành công.");}catch(err){onFail(err,"Lưu safety")}}}><input required value={safetyForm.pattern} onChange={(e)=>setSafetyForm((f)=>({...f,pattern:e.target.value}))}/><button type="submit">Lưu safety</button></form></div>}
{activeTab==="evaluation" && <div><h3>Evaluation</h3><textarea value={evalMessage} onChange={(e)=>setEvalMessage(e.target.value)} /><button disabled={!rid||!evalMessage.trim()||evaluating} onClick={async()=>{try{const out=await runEvalPrompt({variables:{input:{restaurantId:rid,message:evalMessage.trim(),includeDebug:true}}});setEvalResult(out?.data?.evaluateRestaurantAiChatbotPrompt||null);setNotice("Run evaluation thành công.");}catch(e){onFail(e,"Run evaluation")}}}>Run test</button><button onClick={async()=>{try{await createEvalCase({variables:{input:{restaurantId:rid,question:evalMessage.trim(),enabled:true}}});refetchEvalCases?.();setNotice("Đã lưu evaluation case.");}catch(e){onFail(e,"Lưu evaluation case")}}}>Save case</button><button onClick={async()=>{try{const out=await runEvalSet({variables:{input:{restaurantId:rid,includeDebug:false}}});setEvalSetResults(out?.data?.runRestaurantAiChatbotEvaluationSet||[]);setNotice("Đã chạy evaluation set.");}catch(e){onFail(e,"Run evaluation set")}}}>Run enabled set</button>{evalResult?<pre>{JSON.stringify(evalResult,null,2)}</pre>:null}{evalCasesLoading?<p>Đang tải cases...</p>:evalCasesError?<p>{evalCasesError.message}</p>:!(evalCasesData?.restaurantAiChatbotEvaluationCases||[]).length?<p>Chưa có evaluation case.</p>:<ul>{(evalCasesData?.restaurantAiChatbotEvaluationCases||[]).slice(0,10).map((c)=><li key={c.id}>{c.question}</li>)}</ul>}{evalSetResults?.length?<p>Run set results: {evalSetResults.length}</p>:null}</div>}
</section>; }
