import React from "react";
import { act, cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import AiChatbotWidget from "./AiChatbotWidget";

let askMutationSpy, handoffMutationSpy, guestRepliesSpy, guestMessageMutationSpy, publicSettingsQuerySpy;
let socketOn, socketOff, socketEmit, socketDisconnect, connectHandler, staffReplyHandler, handoffResolvedHandler;
vi.mock("socket.io-client", () => ({ io: vi.fn(() => ({ on: socketOn, off: socketOff, emit: socketEmit, disconnect: socketDisconnect })) }));
vi.mock("react-router-dom", async () => ({ ...(await vi.importActual("react-router-dom")), useParams: () => ({ id: "resto-1" }), useLocation: () => ({ pathname: "/restaurant/resto-1" }), useNavigate: () => vi.fn() }));
vi.mock("@apollo/client/react", async () => ({ ...(await vi.importActual("@apollo/client/react")), useMutation: vi.fn((m) => { const b = m?.loc?.source?.body || ""; if (b.includes("AskAiChatbot")) return [askMutationSpy, { loading: false }]; if (b.includes("RequestAiChatbotHandoff")) return [handoffMutationSpy, { loading: false }]; if (b.includes("SendAiChatbotGuestMessage")) return [guestMessageMutationSpy, { loading: false }]; return [vi.fn(), { loading: false }]; }), useLazyQuery: vi.fn(() => [guestRepliesSpy, {}]), useQuery: vi.fn(() => publicSettingsQuerySpy()) }));
const open = () => fireEvent.click(screen.getByRole("button", { name: /Mở ChatBot A.I/i }));
const send = (t) => { fireEvent.change(screen.getByPlaceholderText(/Hỏi về món ăn/i), { target: { value: t } }); fireEvent.click(screen.getByRole("button", { name: /Gửi tin nhắn/i })); };

beforeEach(() => {
  window.localStorage.clear(); window.localStorage.setItem("cohan_ai_guest_id", "guest-1");
  connectHandler = null; staffReplyHandler = null; handoffResolvedHandler = null;
  socketOn = vi.fn((e, cb) => { if (e === "connect") connectHandler = cb; if (e === "aiChatbotStaffReplyCreated") staffReplyHandler = cb; if (e === "aiChatbotHandoffResolved") handoffResolvedHandler = cb; });
  socketOff = vi.fn(); socketDisconnect = vi.fn(); socketEmit = vi.fn((e, p, ack) => { if (e === "joinAiChatbotConversation" && ack) ack({ ok: true }); });
  askMutationSpy = vi.fn().mockResolvedValue({ data: { askAiChatbot: { answer: "Trợ lý đã tiếp nhận.", quickReplies: [], actions: [], contextSummary: null, conversationId: "conv-1" } } });
  handoffMutationSpy = vi.fn().mockResolvedValue({ data: { requestAiChatbotHandoff: { ok: true, handoffRequested: true, message: "Đã gửi yêu cầu gặp nhân viên." } } });
  guestMessageMutationSpy = vi.fn().mockResolvedValue({ data: { sendAiChatbotGuestMessage: { ok: true, conversationId: "conv-1", message: { content: "ok" } } } });
  guestRepliesSpy = vi.fn().mockResolvedValue({ data: { aiChatbotGuestReplies: { handoffClosed: false, conversationStatus: "handoff_requested", replies: [{ id: "2026-05-25T10:00:00.000Z_0", content: "Mình là nhân viên hỗ trợ đây.", senderLabel: "Nhân viên", createdAt: "2026-05-25T10:00:00.000Z" }] } } });
  publicSettingsQuerySpy = vi.fn(() => ({ data: { publicAiChatbotSettings: { enabled: true, welcomeMessage: "Xin chào", starterQuickReplies: ["Gợi ý món bán chạy cho tôi"], handoffEnabled: true, handoffUnavailableMessage: "Không" } }, loading: false, error: null }));
});
afterEach(() => { cleanup(); vi.clearAllTimers(); vi.useRealTimers(); vi.restoreAllMocks(); });

describe("AiChatbotWidget handoff", () => {
  it("uses sendAiChatbotGuestMessage after handoff", async () => { render(<AiChatbotWidget testOverrides={{ disablePolling: true }} />); open(); send("Cần hỗ trợ"); await waitFor(() => expect(askMutationSpy).toHaveBeenCalledTimes(1), { timeout: 1500 }); fireEvent.click(screen.getByRole("button", { name: /Gặp nhân viên/i })); await waitFor(() => expect(handoffMutationSpy).toHaveBeenCalledTimes(1), { timeout: 1500 }); send("Sau handoff"); await waitFor(() => expect(guestMessageMutationSpy).toHaveBeenCalledTimes(1), { timeout: 1500 }); expect(askMutationSpy).toHaveBeenCalledTimes(1); });
  it("shows clear error when guest post-handoff send returns ok=false", async () => { guestMessageMutationSpy.mockResolvedValueOnce({ data: { sendAiChatbotGuestMessage: { ok: false, conversationId: "conv-1", message: { content: "Bạn đang gửi quá nhanh. Vui lòng thử lại sau ít phút." } } } }); render(<AiChatbotWidget testOverrides={{ disablePolling: true }} />); open(); send("Cần hỗ trợ"); await waitFor(() => expect(askMutationSpy).toHaveBeenCalledTimes(1), { timeout: 1500 }); fireEvent.click(screen.getByRole("button", { name: /Gặp nhân viên/i })); await waitFor(() => expect(handoffMutationSpy).toHaveBeenCalledTimes(1), { timeout: 1500 }); send("Tin mới"); await waitFor(() => expect(screen.getByText("Bạn đang gửi quá nhanh. Vui lòng thử lại sau ít phút.")).toBeInTheDocument(), { timeout: 1500 }); });
  it("dedupes same staff reply arriving via socket then polling", async () => { vi.useFakeTimers(); render(<AiChatbotWidget testOverrides={{ pollIntervalMs: 1000 }} />); open(); send("Cần hỗ trợ"); await waitFor(() => expect(askMutationSpy).toHaveBeenCalled(), { timeout: 1500 }); fireEvent.click(screen.getByRole("button", { name: /Gặp nhân viên/i })); await waitFor(() => expect(handoffMutationSpy).toHaveBeenCalledTimes(1), { timeout: 1500 }); await act(async () => connectHandler?.()); await act(async () => staffReplyHandler?.({ id: "2026-05-25T10:00:00.000Z_0", content: "Mình là nhân viên hỗ trợ đây.", senderLabel: "Nhân viên", createdAt: "2026-05-25T10:00:00.000Z" })); await act(async () => { vi.advanceTimersByTime(1100); await Promise.resolve(); }); expect(screen.getAllByText("Mình là nhân viên hỗ trợ đây.")).toHaveLength(1); });
  it("handles aiChatbotHandoffResolved socket event and returns to ask flow", async () => { render(<AiChatbotWidget testOverrides={{ disablePolling: true }} />); open(); send("Cần hỗ trợ"); await waitFor(() => expect(askMutationSpy).toHaveBeenCalled(), { timeout: 1500 }); fireEvent.click(screen.getByRole("button", { name: /Gặp nhân viên/i })); await waitFor(() => expect(handoffMutationSpy).toHaveBeenCalled(), { timeout: 1500 }); await act(async () => handoffResolvedHandler?.({ conversationId: "conv-1", status: "closed", message: "Nhân viên đã kết thúc phiên hỗ trợ." })); send("Sau close"); await waitFor(() => expect(askMutationSpy).toHaveBeenCalledTimes(2), { timeout: 1500 }); expect(guestMessageMutationSpy).toHaveBeenCalledTimes(0); });
  it("closes widget and leaves room", async () => { render(<AiChatbotWidget testOverrides={{ disablePolling: true }} />); open(); send("Cần hỗ trợ"); await waitFor(() => expect(askMutationSpy).toHaveBeenCalled(), { timeout: 1500 }); fireEvent.click(screen.getByRole("button", { name: /Gặp nhân viên/i })); await waitFor(() => expect(handoffMutationSpy).toHaveBeenCalledTimes(1), { timeout: 1500 }); fireEvent.click(screen.getByRole("button", { name: /Đóng chatbot/i })); expect(socketEmit).toHaveBeenCalledWith("leaveAiChatbotConversation", { conversationId: "conv-1", guestId: "guest-1" }); expect(socketDisconnect).toHaveBeenCalled(); });
});
