import React from "react";
import { act, cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import AiChatbotWidget from "./AiChatbotWidget";
let askMutationSpy, handoffMutationSpy, guestRepliesSpy, guestMessageMutationSpy, publicSettingsQuerySpy, guestSendLoadingState;
let socketOn, socketOff, socketEmit, socketDisconnect;
vi.mock("socket.io-client", () => ({ io: vi.fn(() => ({ on: socketOn, off: socketOff, emit: socketEmit, disconnect: socketDisconnect })) }));
vi.mock("react-router-dom", async () => ({ ...(await vi.importActual("react-router-dom")), useParams: () => ({ id: "resto-1" }), useLocation: () => ({ pathname: "/restaurant/resto-1" }), useNavigate: () => vi.fn() }));

const addToCartSpy = vi.fn();
vi.mock("@/context/CartProvider", () => ({ useCart: () => ({ addToCart: addToCartSpy }) }));
vi.mock("@apollo/client/react", async () => ({ ...(await vi.importActual("@apollo/client/react")), useMutation: vi.fn((m) => { const b = m?.loc?.source?.body || ""; if (b.includes("AskAiChatbot")) return [askMutationSpy, { loading: false }]; if (b.includes("RequestAiChatbotHandoff")) return [handoffMutationSpy, { loading: false }]; if (b.includes("SendAiChatbotGuestMessage")) return [guestMessageMutationSpy, { loading: guestSendLoadingState }]; return [vi.fn(), { loading: false }]; }), useLazyQuery: vi.fn(() => [guestRepliesSpy, { loading: false, data: null, error: null }]), useQuery: vi.fn(() => publicSettingsQuerySpy?.() || { data: null, loading: false, error: null }) }));
const open=()=>fireEvent.click(screen.getByRole("button",{name:/Mở ChatBot A.I/i}));
const send=(t)=>{fireEvent.change(screen.getByPlaceholderText(/Hỏi về món ăn/i),{target:{value:t}});fireEvent.click(screen.getByRole("button",{name:/Gửi tin nhắn/i}));};
beforeEach(()=>{addToCartSpy.mockReset();window.localStorage.clear();window.localStorage.setItem("cohan_ai_guest_id","guest-1");guestSendLoadingState=false;socketOn=vi.fn();socketOff=vi.fn();socketEmit=vi.fn();socketDisconnect=vi.fn();askMutationSpy=vi.fn().mockResolvedValue({data:{askAiChatbot:{answer:"Trợ lý đã tiếp nhận.",quickReplies:[],actions:[],contextSummary:null,conversationId:"conv-1"}}});handoffMutationSpy=vi.fn().mockResolvedValue({data:{requestAiChatbotHandoff:{ok:true,handoffRequested:true,message:"Đã gửi yêu cầu gặp nhân viên."}}});guestMessageMutationSpy=vi.fn().mockResolvedValue({data:{sendAiChatbotGuestMessage:{ok:true,conversationId:"conv-1",message:{id:"g1",content:"ok"}}}});guestRepliesSpy=vi.fn().mockResolvedValue({data:{aiChatbotGuestReplies:{handoffClosed:false,conversationStatus:"handoff_requested",replies:[]}}});publicSettingsQuerySpy=vi.fn(()=>({data:{publicAiChatbotSettings:{enabled:true,welcomeMessage:"Xin chào",starterQuickReplies:["Gợi ý món bán chạy cho tôi"],handoffEnabled:true,handoffUnavailableMessage:"Không hỗ trợ"}},loading:false,error:null}));});
afterEach(()=>{cleanup();vi.clearAllTimers();vi.useRealTimers();vi.restoreAllMocks();});
describe("basic",()=>{
it("normal AI flow before handoff",async()=>{render(<AiChatbotWidget testOverrides={{disableSocket:true,disablePolling:true}}/>);open();send("Xin chào");await waitFor(()=>expect(askMutationSpy).toHaveBeenCalledTimes(1),{timeout:1500});expect(screen.getByText("Trợ lý đã tiếp nhận.")).toBeInTheDocument();expect(guestRepliesSpy).not.toHaveBeenCalled();});
it("shows friendly message when ask is rate limited",async()=>{askMutationSpy.mockRejectedValueOnce({graphQLErrors:[{message:"Bạn đang gửi quá nhanh. Vui lòng thử lại sau ít phút.",extensions:{code:"RATE_LIMITED"}}]});render(<AiChatbotWidget testOverrides={{disableSocket:true,disablePolling:true}}/>);open();send("Xin chào");await waitFor(()=>expect(screen.getByText("Bạn đang gửi quá nhanh. Vui lòng thử lại sau ít phút.")).toBeInTheDocument(),{timeout:1500});});
it("prevents rapid quick-reply double submit while in flight",async()=>{let release;askMutationSpy.mockImplementationOnce(()=>new Promise((r)=>{release=r;}));render(<AiChatbotWidget testOverrides={{disableSocket:true,disablePolling:true}}/>);open();const quick=screen.getByRole("button",{name:"Gợi ý món bán chạy cho tôi"});fireEvent.click(quick);fireEvent.click(quick);expect(askMutationSpy).toHaveBeenCalledTimes(1);await act(async()=>release({data:{askAiChatbot:{answer:"ok",quickReplies:[],actions:[],contextSummary:null,conversationId:"conv-1"}}}));});
it("disables input while guest send is loading",()=>{guestSendLoadingState=true;render(<AiChatbotWidget testOverrides={{disableSocket:true,disablePolling:true}}/>);open();expect(screen.getByPlaceholderText(/Hỏi về món ăn/i)).toBeDisabled();});
it("hides handoff action when handoffEnabled=false",async()=>{publicSettingsQuerySpy=vi.fn(()=>({data:{publicAiChatbotSettings:{enabled:true,welcomeMessage:"Xin chào",starterQuickReplies:["Gợi ý món bán chạy cho tôi"],handoffEnabled:false,handoffUnavailableMessage:"Không hỗ trợ"}},loading:false,error:null}));askMutationSpy.mockResolvedValueOnce({data:{askAiChatbot:{answer:"ok",quickReplies:[],actions:[{type:"navigate",label:"Mở menu",href:"/menu"},{type:"handoff",label:"Gặp nhân viên",href:"/support"}],contextSummary:null,conversationId:"conv-1"}}});render(<AiChatbotWidget testOverrides={{disableSocket:true,disablePolling:true}}/>);open();send("Xin chào");await waitFor(()=>expect(askMutationSpy).toHaveBeenCalledTimes(1),{timeout:1500});expect(screen.getByRole("button",{name:"Mở menu"})).toBeInTheDocument();expect(screen.queryByRole("button",{name:"Gặp nhân viên"})).not.toBeInTheDocument();
it("renders menu card and add-to-cart flow", async()=>{askMutationSpy.mockResolvedValueOnce({data:{askAiChatbot:{answer:"Gợi ý cho bạn",intent:"menu",quickReplies:[],actions:[],contextSummary:null,conversationId:"conv-1",sources:[{type:"menuItem",id:"food-1",label:"Phở bò",formattedPrice:"90.000đ",isAvailable:true,restaurantId:"resto-1"}]}}});render(<AiChatbotWidget testOverrides={{disableSocket:true,disablePolling:true}}/>);open();send("gợi ý món");await waitFor(()=>expect(screen.getByText("Phở bò")).toBeInTheDocument());expect(screen.getByRole("button",{name:"Xem món"})).toBeInTheDocument();fireEvent.click(screen.getByRole("button",{name:"Thêm vào giỏ"}));expect(addToCartSpy).toHaveBeenCalled();expect(screen.getByText(/Đã thêm Phở bò vào giỏ/)).toBeInTheDocument();});
});
});
