import React, { Suspense, lazy, useState, useEffect, useMemo, useContext } from "react";
import Sidebar from "../components/Dashboard_Manager/Sidebar";
import Header from "../components/Dashboard_Manager/Header";
import "./ManagerLayout.scss";
import "./ManagerUnifiedBackground.css";
import "../components/Dashboard_Manager/Customer/AiChatbotAdminDashboardScale.scss";
import { AuthContext } from "@/context/AuthContext";
import { isAccountantRole, isHrRole, isManagerRole, isAdminRole } from "@/utils/frontendRoleAccess";
import { filterNavigationByPermissionAccess } from "@/utils/frontendPermissionAccess";
import useManagerRestaurantSelection from "@/hooks/useManagerRestaurantSelection";
import useCommunication from "@/hooks/useCommunication";

const Dashboard = lazy(() => import("../components/Dashboard_Manager/Dashboard"));
const ManagerAnalyst = lazy(() => import("../components/Dashboard_Manager/Analyst/ManagerAnalyst"));
const ReportsManagement = lazy(() => import("../components/Dashboard_Manager/Reports/ReportsManagement"));
const StaffManagement = lazy(() => import("../components/Dashboard_Manager/Staff/StaffManagement"));
const ScheduleManagementPage = lazy(() => import("../components/Dashboard_Manager/Schedule/ScheduleManagementPage"));
const OrderManagement = lazy(() => import("../components/Dashboard_Manager/Order/OrderManagement"));
const MenuManagement = lazy(() => import("../components/Dashboard_Manager/Menu/MenuManagement"));
const ComboManagement = lazy(() => import("../components/Dashboard_Manager/Combo/ComboManagement"));
const ModifierManagement = lazy(() => import("../components/Dashboard_Manager/ModifierManagement"));
